In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Metadata stats and merging metadata files (3 studies)

## Merging the metadata files

In [ ]:
import pandas as pd

# List of CSV file names
file_names = ['./AMP_AD_datasets/ROSMAP_metadata_v1.csv', 
              './AMP_AD_datasets/MSBB_metadata_v1.csv', 
              './AMP_AD_datasets/MAYO_metadata_v1.csv']

# Empty list to hold DataFrames
dfs = []

# Columns to ensure are in each DataFrame
required_columns = ['race', 'spanish', 'ethnicity']

# Step 1: Read each CSV file and process
for file_name in file_names:
    # Read the CSV file
    df = pd.read_csv(file_name)
    
   
    # Ensure all required columns are present, add them if they are not
    for column in required_columns:
        if column not in df.columns:
            df[column] = pd.NA
    
    df['study'] = file_name.split('/')[2].split('_')[0]
            
    # Append to the list of DataFrames
    dfs.append(df)

# Use the column order of the first DataFrame for all others, including any new columns
column_order = dfs[0].columns.tolist()

# Reorder and concatenate, ensuring all DataFrames have the same column order
merged_df = pd.concat([df.reindex(columns=column_order) for df in dfs], ignore_index=True)

# Step 5: Save the merged DataFrame to a new CSV file
merged_df.to_csv('./merged_metadata.csv', index=False)

## Mapping values to numerics in merged metadata

In [ ]:
import pandas as pd

# Path to your CSV file
file_path = './merged_metadata.csv'

# Load the CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

# Dictionaries for conversion
diagnosis = {'AD':1, 'CT':0, 'OTHER':2, 'PSP':3, 'PATH_AGE':4}
sex = {'male': 0, 'female': 1}
tissue = {'ACC': 1, 'CBE': 2, 'DLPFC': 3, 'FP': 4, 'IFG': 5, 'PCC': 6, 'PHG': 7, 'STG': 8, 'TCX': 9}

# Convert values in the 'diagnosis', 'sex', and 'tissue' columns using the map method
df['diagnosis'] = df['diagnosis'].map(diagnosis)
df['sex'] = df['sex'].map(sex)
df['tissue'] = df['tissue'].map(tissue)

# Change '90+' value in the 'age_death' column to 90
df['age_death'] = df['age_death'].replace('90+', 90)

# Save the modified DataFrame back to a new CSV file
df.to_csv('./metadata_v1.csv', index=False)

## Stats

In [1]:
import pandas as pd
file_path = './metadata_merged.csv'  
df = pd.read_csv(file_path)
df

,specimenID,individualID,diagnosis,tissue,race,spanish,apoe4_allele,sex,batch,pmi,RIN,RIN2,age_death,AlignmentSummaryMetrics_PCT_PF_READS_ALIGNED,RnaSeqMetrics_PCT_INTRONIC_BASES,RnaSeqMetrics_PCT_INTERGENIC_BASES,RnaSeqMetrics_PCT_CODING_BASES,ethnicity,study
0,487_120515,R9904978,0,3,1.0,2.0,0,0,4,12.433333,6.9,47.61,72.720055,0.931411,0.225013,0.058488,0.342722,NaN,ROSMAP
1,182_120424,R9818080,0,3,1.0,2.0,0,0,7,16.000000,8.4,70.56,81.111567,0.944450,0.172408,0.041036,0.394201,NaN,ROSMAP
2,193_120424,R9817161,1,3,1.0,2.0,0,1,4,1.750000,7.1,50.41,80.906229,0.958718,0.203963,0.048166,0.357855,NaN,ROSMAP
3,694_120605,R9817056,0,3,1.0,2.0,0,0,4,6.416667,7.1,50.41,87.753593,0.960609,0.201002,0.045065,0.397276,NaN,ROSMAP
4,366_120502,R9809661,1,3,1.0,2.0,1,1,7,17.416667,7.4,54.76,90.000000,0.931962,0.205742,0.048650,0.378299,NaN,ROSMAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2100,948_CBE,948,1,2,NaN,NaN,0,1,24,4.000000,7.9,62.41,82.000000,0.971513,0.218398,0.102550,0.312080,NaN,MAYO
2101,952_CBE,952,1,2,NaN,NaN,1,1,30,3.000000,9.0,81.00,83.000000,0.970183,0.289034,0.107290,0.266025,NaN,MAYO
2102,966_CBE,966,1,2,NaN,NaN,2,1,22,16.000000,8.8,77.44,79.000000,0.971717,0.143079,0.069472,0.374848,NaN,MAYO
2103,976_CBE,976,1,2,NaN,NaN,1,1,19,7.000000,8.3,68.89,90.000000,0.975052,0.134213,0.080812,0.370581,NaN,MAYO
2104,991_CBE,991,1,2,NaN,NaN,1,0,27,12.077553,9.3,86.49,87.000000,0.966562,0.128365,0.122418,0.333899,NaN,MAYO

In [15]:


# Count the number of unique values in each column of the filtered DataFrame
unique_values_per_column = df.nunique()

# Print the number of unique values in each column
print(unique_values_per_column)

specimenID                                      2105
individualID                                     835
diagnosis                                          2
tissue                                             9
race                                               4
spanish                                            2
apoe4_allele                                       3
sex                                                2
batch                                             33
pmi                                              362
RIN                                              141
RIN2                                             141
age_death                                        215
AlignmentSummaryMetrics_PCT_PF_READS_ALIGNED    2060
RnaSeqMetrics_PCT_INTRONIC_BASES                2102
RnaSeqMetrics_PCT_INTERGENIC_BASES              2069
RnaSeqMetrics_PCT_CODING_BASES                  2099
ethnicity                                          5
study                                              3
dtype: int64

In [3]:
sex_counts = df['sex'].value_counts()
print(sex_counts)

sex
1    1294
0     811
Name: count, dtype: int64

In [16]:
diagnosis_counts = df1['diagnosis'].value_counts()
print(diagnosis_counts)

diagnosis
1    1363
0     742
Name: count, dtype: int64

In [93]:
file_path = './metadata_merged.csv'  # Replace 'your_file_path.csv' with the path to your actual CSV file
df = pd.read_csv(file_path)

# Check the number of samples per tissue type
tissue_counts = df['tissue'].value_counts()

# Print the counts
print("Number of samples per tissue type:")
print(tissue_counts)

Number of samples per tissue type:
tissue
3    436
1    265
6    250
7    226
8    220
4    215
5    201
9    148
2    144
Name: count, dtype: int64

# Merging three Bulk RNA-seq Datasets, harmonizing, and filtering genes sets as features

Filtering the RNAseq datasets (genes and samples)

## Harmonizing genes throughout three datasets (separately)

In [5]:
rnaseq = pd.read_csv('./AMP_AD_datasets/ROSMAP_Residualized_counts_(age-death).tsv', sep='\t', header=None).T

# Set the first row as the header
rnaseq.columns = rnaseq.iloc[0]

# Drop the first row as it's now set as the header
rnaseq = rnaseq[1:]

# Set the first column as the index
rnaseq.set_index(rnaseq.columns[0], inplace=True)


rnaseq

/tmp/ipykernel_39067/1349606160.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1409,1410,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100,2101,2102,2103,2104,2105,2106,2107,2108,2109,2110,2111,2112,2113,2114,2115,2116,2117,2118,2119,2120,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,2131,2132,2133,2134,2135,2136,2137,2138,2139,2140,2141,2142,2143,2144,2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,2158,2159,2160,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2220,2221,2222,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2255,2256,2257,2258,2259,2260,2261,2262,2263,2264,2265,2266,2267,2268,2269,2270,2271,2272,2273,2274,2275,2276,2277,2278,2279,2280,2281,2282,2283,2284,2285,2286,2287,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303,2304,2305,2306,2307,2308,2309,2310,2311,2312,2313,2314,2315,2316,2317,2318,2319,2320,2321,2322,2323,2324,2325,2326,2327,2328,2329,2330,2331,2332,2333,2334,2335,2336,2337,2338,2339,2340,2341,2342,2343,2344,2345,2346,2347,2348,2349,2350,2351,2352,2353,2354,2355,2356,2357,2358,2359,2360,2361,2362,2363,2364,2365,2366,2367,2368,2369,2370,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380,2381,2382,2383,2384,2385,2386,2387,2388,2389,2390,2391,2392,2393,2394,2395,2396,2397,2398,2399,2400,2401,2402,2403,2404,2405,2406,2407,2408,2409,2410,2411,2412,2413,2414,2415,2416,2417,2418,2419,2420,2421,2422,2423,2424,2425,2426,2427,2428,2429,2430,2431,2432,2433,2434,2435,2436,2437,2438,2439,2440,2441,2442,2443,2444,2445,2446,2447,2448,2449,2450,2451,2452,2453,2454,2455,2456) have mixed types. Specify dtype option on import or set low_memory=False.
  rnaseq = pd.read_csv('./AMP_AD_datasets/ROSMAP_Residualized_counts_(age-death).tsv', sep='\t', header=None).T

,ENSG00000000003,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,ENSG00000001460,...,ENSG00000288030,ENSG00000288033,ENSG00000288044,ENSG00000288048,ENSG00000288049,ENSG00000288061,ENSG00000288062,ENSG00000288075,ENSG00000288107,ENSG00000288108
feature,,,,,,,,,,,,,,,,,,,,,
510_120515,0.547178095212917,0.0309218787590315,-0.0372678350757441,0.396124646614575,0.432101014475444,1.2173794211485,0.00184357604205262,-0.140853888875604,-0.0846701267847237,0.107804287085237,...,-0.019012,-1.011139,-0.476464,0.038422,-0.106956,-0.168893,-0.619431,-0.277664,-0.156056,-0.468432
207_120424,-0.466698175292601,-0.097938553258727,-0.0709106002656966,0.337465773675399,0.418961040098725,-0.0767611780301326,-0.206077526876193,-0.192994069034581,-0.0707552325529832,0.125610196786115,...,0.464913,-0.494513,-0.322938,0.248319,-1.197898,-0.064117,0.066651,-0.713536,0.639593,1.281982
81_120417,0.021058836508973,-0.00130081588164402,0.287300932732309,0.142445519279894,0.853906096000501,0.513618640911416,-0.434044546548744,-0.430917973099305,-0.396874845609266,-0.0482636079044048,...,-0.973615,0.447193,0.284568,-0.365754,-1.192738,0.811934,-0.233031,0.205384,0.172358,0.235588
649_120529,0.932153793701418,0.175135505673658,0.0768413389176011,-0.484958454505552,-0.858708587093736,-0.273069212454823,0.0768352247447077,0.328137474073671,-0.0716498134906481,0.324524781916795,...,-0.766962,-0.472437,-0.687248,0.00333,0.309679,-0.105628,-0.325996,0.291254,-0.170534,0.527559
487_120515,-0.832440008601364,0.110146830267783,0.144344480774273,-0.112420584036463,-0.498994438928982,0.691244142360738,-0.844905882644524,-1.26032416418812,-0.371007751379133,0.218281528783633,...,0.26475,-0.302026,-0.356258,0.488189,-0.514658,-0.000205,0.013918,0.801652,1.875648,0.060518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RISK_84_redo,0.675761108168252,0.327420793379606,0.487027691294158,0.0838413948487905,0.737589269664486,1.08757354904832,0.234150891258945,0.337132422723094,0.0407395431818992,-0.303667166693484,...,0.400455,0.291289,-1.575512,1.326077,0.349736,-0.480606,0.971165,-0.135923,0.488347,1.665342
RISK_9_rerun,-0.54626276839276,-0.0539197707375027,-0.178287526141687,-0.283913738073636,-0.71556248594123,-1.5291401239508,-0.504561826072045,-0.229724215597815,-0.429624525112165,0.337475734707598,...,0.056668,-0.632197,-0.746504,-0.131247,-1.094803,-1.012821,-0.343336,0.195717,-0.617691,1.022608
RISK_93,0.504201542299034,0.20235041178395,0.298144698198822,0.121036560985348,-0.159570962193653,-0.173865559619338,0.0455031549998374,0.123694236067999,0.0308491478959837,-0.581814680587119,...,0.866037,-0.476356,1.494109,0.099155,1.179052,-0.250564,0.371609,0.284761,0.527348,2.260204
RISK_94,0.356525716520059,0.237729964019099,0.166071398180446,0.0561579649869614,-0.589365887833161,-0.486405712762818,0.0654347095611836,0.0802847740682909,-0.0880065004325445,-0.0838374811856119,...,0.133441,0.517389,0.975004,0.294747,-0.745655,0.368008,-0.080536,-0.033209,-0.565935,1.93407
RISK_97,-0.0307273917433946,0.325485578189496,0.170935918120915,-0.217593048146873,-0.0945991218448621,-0.0446358924306769,-0.0920501645767283,-0.137075460748986,-0.271081606240932,-0.114806434772462,...,0.298146,0.716534,0.903274,-0.015395,2.352974,-0.506116,0.186001,-0.228021,1.589673,-0.14791

In [ ]:
# Common ensembl IDs between all the datasets

import pandas as pd

# Define a function to load, transpose, and set the first row as header
def load_and_prepare(filepath):
    # Load the file, without headers, then transpose
    df = pd.read_csv(filepath, sep='\t', header=None).T
    # Set the first row as the header
    df.columns = df.iloc[0]
    # Remove the first row now that it's set as the header
    df = df[1:]
    # Set the first column as the index
    df.set_index(df.columns[0], inplace=True)
    return df

# Load and prepare each dataset
df1 = load_and_prepare('./AMP_AD_datasets/ROSMAP_Residualized_counts_(age-death).tsv')
df2 = load_and_prepare('./AMP_AD_datasets/MSBB_Residualized_counts_(age-death).tsv')
df3 = load_and_prepare('./AMP_AD_datasets/Mayo_Residualized_counts_(age-death).tsv')

# Get the column names as sets
columns1 = set(df1.columns)
columns2 = set(df2.columns)
columns3 = set(df3.columns)

# Find the intersection of column names
common_columns = columns1 & columns2 & columns3

 Clean the datasets and export -- ensembl IDs to gene symbol

In [ ]:
import pandas as pd

# Load the gene ID conversion file
id_conversion_path = './david_genes_conversion.txt'
id_conversion = pd.read_csv(id_conversion_path, sep='\t')

# Create a dictionary to map Ensembl IDs to Gene Names
gene_map = dict(zip(id_conversion['From'], id_conversion['To']))
gene_map

In [54]:
# This block of code was repeated in the original script, so we can remove it to avoid redundancy.

# Define a function to load, transpose, filter, rename, convert to float, and export a dataset
def process_dataset(file_path, gene_map, output_path):
    # Load the dataset, manage mixed data types warning by setting low_memory to False
    df = pd.read_csv(file_path, sep='\t', header=None, low_memory=False).T
    
    # Set the first row as the header (column names are Ensembl IDs)
    df.columns = df.iloc[0]
    df = df[1:]
    
    # Set the first column as the index
    df.set_index(df.columns[0], inplace=True)
    
    # Convert all gene expression data to float
    df = df.apply(pd.to_numeric, errors='coerce')
    
    # Filter columns based on gene_map keys (Ensembl IDs)
    filtered_df = df.loc[:, df.columns.isin(gene_map.keys())]
    
    # Rename the columns using the gene_map
    filtered_df.rename(columns=gene_map, inplace=True)
    


    # Export the DataFrame
    filtered_df.to_csv(output_path)
    # print(final_df)

# Path to one of the datasets
dataset_path = './AMP_AD_datasets/Mayo_Residualized_counts_(diagnosis).tsv'
output_path = './AMP_AD_datasets/Mayo_v2_samples.csv'

# Process the dataset
process_dataset(dataset_path, gene_map, output_path)

/tmp/ipykernel_760/432076196.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.rename(columns=gene_map, inplace=True)

## Merging

In [101]:
import pandas as pd

# Load the datasets
df1 = pd.read_csv('./AMP_AD_datasets/ROSMAP_v2_samples.csv', index_col=0)
df2 = pd.read_csv('./AMP_AD_datasets/MSBB_v2_samples.csv', index_col=0)
df3 = pd.read_csv('./AMP_AD_datasets/Mayo_v2_samples.csv', index_col=0)

# Concatenate the datasets
# Assuming all datasets have the same columns (genes) and the rows (samples) need to be merged
# combined_df = pd.concat([df1, df2, df3], axis=0)

# If you need to ensure that the genes align correctly and are consistent across datasets, you could also include:
combined_df = pd.concat([df1, df2, df3], axis=0, join='inner')

# Check the combined DataFrame
combined_df.shape

(2105, 15302)

In [109]:
combined_df

,TSPAN6,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,NFYA,STPG1,...,RENO1,LOC105376030,LOC107986626,LOC102724289,LINC03026,LOC124902204,LOC107986742,LOC283045,LOC105377224,LOC101929748
specimenID,,,,,,,,,,,,,,,,,,,,,
487_120515,-1.311624,0.198351,0.459366,-0.130345,-0.595326,0.213454,-1.238362,-1.728809,-0.548562,0.509772,...,0.662136,1.194861,-0.334757,0.137462,0.108735,0.484869,1.437143,0.318347,-0.517982,-0.034570
182_120424,-1.142552,0.223985,0.388770,-0.392290,-0.865868,-1.848168,-0.723939,-0.542297,-0.228433,0.482190,...,-0.048871,1.534010,0.574645,-0.322134,-0.450281,0.719957,1.119835,0.232768,0.684921,0.110800
193_120424,-1.098726,0.310779,0.890378,-0.144169,-0.920858,-1.445022,-0.667666,-0.779523,-0.414912,0.650459,...,-0.208040,1.039052,0.539163,-0.148980,-1.037118,0.550380,0.794598,0.346907,0.159491,0.197251
694_120605,-0.274357,0.032824,0.248784,-0.431776,0.467455,-0.468727,-0.318939,-0.098791,-0.107479,0.156766,...,-0.400270,0.654342,0.367132,0.265392,-1.404352,0.695118,-0.187372,0.114395,-0.484565,-0.019248
366_120502,-0.618033,0.084906,0.357523,0.216940,0.752710,-0.303869,-0.604859,-0.287414,-0.233574,0.435989,...,-0.470331,1.440713,-0.662369,-0.756617,-1.037525,0.043755,0.513285,0.094453,0.398065,0.133158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948_CBE,-0.426868,-0.104909,0.008333,-0.678367,-0.331839,0.131425,0.212101,-0.070641,0.047432,0.236184,...,-0.522347,0.532042,0.456984,-0.103929,0.666553,0.193082,0.279276,0.172546,-1.416390,-0.101523
952_CBE,-0.511010,-0.196173,-0.537725,-1.452138,0.469393,-2.132757,-0.703451,-0.848650,-0.519402,0.363786,...,0.858857,-0.281561,0.084446,0.311883,0.250254,-0.249922,0.854351,-0.965282,-1.601522,1.230199
966_CBE,-0.025363,-0.000323,0.003503,0.243032,-0.633469,0.034772,-0.310798,-0.079054,0.203078,0.026697,...,0.280892,-0.187527,0.326858,0.498738,-0.556654,-0.165566,-0.595309,0.576540,-1.312718,0.224004
976_CBE,0.672469,-0.035666,0.233930,0.217314,0.505145,0.679639,0.146305,0.296122,-0.151400,-0.156085,...,-0.457740,0.517132,-0.191756,0.036250,0.008297,-0.350369,-0.226253,-0.103642,-1.281930,-0.624040
991_CBE,0.888483,0.044687,-0.333468,-0.115190,0.368081,0.691629,0.033943,0.370386,-0.030560,-0.118024,...,0.223740,-1.857678,-0.559610,0.174379,-0.293122,-0.367931,-0.241495,-1.042724,-0.350711,0.139999

In [110]:
combined_df.to_csv('rnaseq_merged_13k.csv')

Checking

In [112]:
df = combined_df
# Check for NULL values in the dataset
null_values_exist = df.isnull().any().any()

if null_values_exist:
    print("There are NULL values in the dataset.")
else:
    print("There are no NULL values in the dataset.")

There are no NULL values in the dataset.

In [15]:
import pandas as pd
from statsmodels.robust.scale import mad

# Calculate the Median Absolute Deviation (MAD) for each gene (column)
mad_values = df.apply(mad, axis=0)

# Rank the genes based on MAD values from most variable to least variable
ranked_genes = mad_values.sort_values(ascending=False).index.tolist()

# Select the top 4000 most variable genes
most_variable_genes = ranked_genes[:4000]

# Print the ranked list of genes
# print("Ranked genes from most variable to least variable:")
# print(ranked_genes)
print('Top 4000 most variable genes:')
print(most_variable_genes)

Top 4000 most variable genes:

In [16]:
for i in most_variable_genes:
    print(i)

GSTM1
CARTPT
MIR3976HG
LINC02263
PVALB
LINC00507
LINC01164
CTXN3
ROS1
SLC27A6
LINC01007
POSTN
LINC00898
GPR26
MEPE
SLC17A6
PENK
DNAJC5G
MAS1
C6orf141
RTP1
LNCBRM
PTGER3
SERPINA5
KLK7
LOC124902301
HSPB3
PCSK1
FREM3
LOC124900989
CBLN4
CBLN2
LOC105369302
PART1
TRIM54
TNNT2
MME
CNGB1
ASB2
TDO2
BMP3
TYRP1
EPIC1
LINC02714
CCK
INSRR
LINC00326
LINC02607
FGF5
TESPA1
MT1H
PNMA5
PKD2L1
SOSTDC1
LOC105371672
SMIM43
ONECUT2
TMEM233
SMPX
KCNS1
SMYD1
SCARA5
GPR55
HTR3B
CRNDE
KRT17
NEUROD6
DRGX
RXFP1
PTH2R
GDA
MCHR2
FBXO40
IQGAP3
SLCO4C1
LOC124900848
MET
CHGA
LINC01511
NGB
MSC
LTF
THSD4-AS1
KLHL14
SERTM1
LOC101929237
SV2C
ATP4A
LCN15
PCP4
LINC02217
COL5A2
CALB1
LINC02552
NOS2
CERKL
HTR2C
RGS4
DPP4
OBSCN-AS1
WNT2
PRSS16
HTR1A
KCNH5
LINC01821
ADAMTS2
MSC-AS1
PTPN3
GLP2R
KCNC2
LINC01361
OTOGL
SST
SERPINA3
UMODL1-AS1
FAM163A
LAMC2
ABCC12
TAC1
SP8
KCNV1
SLC17A8
DYDC2
CNIH3-AS2
HSPA6
THEMIS
SOHLH1
CFAP157
GLRA3
LINC02009
CRABP1
SCRT2
LINC02458
PRLR
MAPK15
FOXJ1
VWA3B
GDF7
ANKRD34C
LINC03025
HS3ST3B1
AQP1
COL1A1
SEC16B
TNC
PAX7
SHISA2
GPR150
LOC105370525
SOWAHB
FIBCD1
NCALD
AGBL1
PDYN
FAM162B
LINGO2
FFAR4
SLC47A2
SERPINI2
HGF
IL12A-AS1
C10orf105
TBR1
RAD51AP2
LPAR4
LOC102724560
HTR2A
LINC02347
ADRA2B
KL
SATB2-AS1
DAW1
RSPO2
VIP
VGLL3
CHRNA2
KCNS2
LOXL1-AS1
TMEM132E-DT
SLC22A9
CHI3L2
NWD2
SLC30A3
RTKN2
CREG2
PWWP3B
ZMYND10
IL13RA2
LINC02963
SPARC
LINGO3
ENC1
HS3ST2
SSTR3
GPR6
DBH
LINC01182
CCDC68
EGFLAM
RGS8
RAB27B
STAT4
NEFL
APOC1
STK26
TMEM200B
LOXHD1
NEFH
CELSR1
KCNB2
GLP1R
GABRA1
TAFA1
YBX2
EMX1
PRDM8
SAMD11
BDNF
HTR1D
ANO3
GOLT1A
KCTD4
GCSIR
DUXAP8
ALDH1A3-AS1
PKD1P2
CCBE1
MCHR1
ADAMTS18
OTX1
GFRA2
BMP4
CUX2
VSTM5
SPTSSB
PLEKHD1
ADTRP
TRABD2A
CA12
RET
TAFA2
HKDC1
LOC105376654
SLC22A10
RTN4RL2
TUNAR
LOC102724934
PTPRT
VWC2L
RPRM
PTPN7
EPN3
NELL1
LOC105378231
PLIN1
PTGS2
USH1C
NKD2
IKZF3
RSPH4A
DIO2
STAC
COL8A1
LINC00923
NEUROD1
LY86-AS1
RGS1
OPN4
ADRA1B
MIR31HG
EPCAM
ACP5
LINC01484
TRBC2
FAM87A
KLF5
ARMC3
GRB14
CCL2
FMN1
OSTN
TLX2
CES1
RASL12
PCP4L1
RHEBL1
NEFM
LHX2-AS1
LGR6
OR7A5
PPEF1
PRRG4
FLT3
MEI4
NPY
LCTL
QPCT
SHISA8
VSNL1
TOX2
MEF2C
LOC101928416
ZNF732
IL17RE
SLC27A2
CACNA1H
MEIS3
LINC02984
ANK1
SLC16A12
BSPRY
TNFRSF11B
IL1RL1
MC4R
PRR29
HAGLR
PHOSPHO1
C8orf34-AS1
SLC22A18
LINC00940
GINS3
BLACAT1
POPDC3
MKX
C3
USP43
CALHM1
C3orf80
DLX6
CFAP65
CA4
IGFBPL1
RPL13P12
CHI3L1
TPBG
KCNK9
CIMAP1B
ZBBX
NPY2R
CNN1
IL12RB2
LINC01819
PNMA6F
ABTB3
GPC3
OSR1
PIK3R6
CLSTN2
CFAP57
ALKAL2
GPR88
FER1L6-AS2
OPN3
CD44
RFX8
GABRA3
POU6F2
FGF9
CDH13
SLCO2A1
NIPAL1
LOC284798
LANCL3
NXPH2
GRIN3A
FAM81A
VAX1
ANKRD22
PKP3
SERPINE1
NPPC
MPPED1
FBLN7
VWC2
SLC26A4
TMEM45A
RORB
CFAP47
RASL11A
COL17A1
LINC02525
SHD
TRPC5
SERPINF1
LINC00460
ICOSLG
VAMP1
OTOF
FAM163B
C1QL3
SLC35F4
COCH
CCDC158
DRD2
FXYD7
GRM2
SHC3
KCNJ5-AS1
VPS9D1-AS1
IGF2BP2
BEND4
SFRP4
SPACDR
CRHR2
MMRN1
DCLK3
SUSD2
FAM95C
LYPD6B
PRIMA1
SIGLEC1
CHRM3
LPAR3
FAT2
COL12A1
DACT2
INSM1
LOC400553
LINC02082
TDRD5
PPL
ZDHHC12-DT
ODAD1
TMEM200C
OGN
PDE10A
CPNE9
ABCG8
HTR1F
LAMP5
HRK
DLX5
LINC02043
CFAP300
APOL4
LDLRAD4-AS1
CPNE4
SLC44A5
RRAD
LOC105373289
CYP4F3
HSPA7
FEZF2
HSPA1A
MYH11
BAIAP3
CRH
TCERG1L
DLX1
MLIP
CLMP
DACH1
LINC01948
TCAP
S100A8
RAB37
LINC01234
CLEC18B
CCDC78
AUNIP
LINC02232
MS4A14
SHISA3
ECHDC3
DIRAS3
MGP
COL26A1
SLC1A7
RTP5
STC1
LINC01010
WDR49
RTBDN
CENPVL3
OPRM1
LETR1
CP
LOC102724594
PCDH19
PNMT
MUC12
KRT5
MPZL3
SDR16C5
GAD2
CYP4F26P
HSD11B2
TEKT2
CNTNAP2
P2RY2
LINC01115
JPH2
LHFPL1
RSPO3
KCNG1
ADCYAP1
SPHK1
LINC00463
CHRM5
APLNR
PALM3
LINC00598
C2CD4C
STC2
IL1B
TC2N
ZNF503-AS2
LPL
ARSF
C1QL2
LOC105376121
TDRD12
SSTR1
TRPC3
HLA-DRB5
EVPL
CASQ1
SCIN
CCR5
ADAMTS16-DT
KLB
CASQ2
KCNJ3
PLCXD3
UNC5D
WFIKKN2
NGFR
DLGAP1-AS3
GALNTL5
LDB2
DIRAS2
LRRC2
EFNA5
ECE2
OLFM3
SLC38A8
GABRB2
SMIM32
C4B
SINHCAF
SPAG6
DHRS9
LOC124902128
NREP
LOXL1
EGR2
CACNA2D4
LINC01574
STK31
SLC32A1
CTXN1
LOC105371735
HLA-DPB2
VGF
FOXO6
PKD1P5
PIRT
SYT2
ATRNL1
ARHGEF4-AS1
LOC101927636
LINC01978
CACNA1G
RPH3A
CD180
GNG2
MT1A
CD163
ISLR
SCUBE1
MORN5
BEST1
CXCL2
PIF1
LSMEM2
SLC6A7
PAX8
LINC01299
VWA3A
ANO1
IGFN1
LRAT
FMO2
TRHDE
LILRB5
SPMIP4
GJB2
HOPX
KCNAB3
EPOP
GPR52
MDFI
CNMD
RHOV
SRPX
WNT9A
LINC00886
PCK1
MYO5B
TK1
EFCAB10
NT5C1A
CFAP20DC-AS1
RIBC1
FCGBP
ERVMER34-1
LINC02361
CCDC80
POU3F4
DNAH11
MFSD2B
TRIM36
ITPRIPL1
MIR4500HG
STUM
STMN2
SV2B
SLC17A7
C11orf87
GPAT3
CXCL5
HAMP
SMPD4P1
CXCL1
LNC-LBCS
HEY2-AS1
CD24
CACNG8
PRSS35
HCN1
KLHL6
PCDH11Y
CYP39A1
CAPS
IRF6
ALDH1A3
SYTL5
COL25A1
BHLHE22
TMEM158
TNFAIP8L3
COL3A1
ADORA2A
S100A4
LDAF1
PKDCC
XKR9
MIR124-2
PAH
LINC00865
CABP1
VSTM2A-OT1
MAEL
SERPINI1
AEBP1
ANKRD45
RGS14
FCRLB
LOC100507336
KCTD16
HPCA
LOC105372703
TMEM156
PNOC
LINC02857
TMEM272
MAG
FLT4
DIO3OS
VCAM1
HPGDS
ADRA2A
ADAMTS14
S100A9
ELAVL4
RNU6-529P
PCED1B-AS1
CLEC4E
TMEM235
IMPG1
GRID2IP
FHDC1
CAMK4
VIPR2
CRHR1
PDK4
CHST8
RFPL2
PPM1J
LOC102723996
MRC2
TMEM88B
KCNJ2-AS1
RMST
GIPR
OR7C1
LIPG
NPAS1
CLEC9A
PKP1
LOC339260
SYNDIG1L
SNAP25
SYN1
ACY3
LYZ
PGM2L1
TRIP13
VAT1L
LCIIAR
LOC102724058
AK7
HTR6
CHRM4
SIGLEC9
GALNT8
LINC01962
LOC105376030
BISPR
NPIPA5
STEAP1
MYLK3
FLRT3
PNMA8B
GJD2
FPR3
LOC100287808
LOC107986669
STAC2
KLK6
CRACR2B
OSBPL3
LINC01736
PLCXD2
MFAP4
MYO15A
TOX3
CNTN5
LOC101929473
CHKB
ZNF365
CLEC5A
IPCEF1
NHSL2
CNTNAP5-DT
SIX4
LINC02381
DLEC1
ADPRHL1
CD22
C4A
FZD7
COL22A1
SPTLC3
LINC02192
ABCA1
DRD1
FOS
HS6ST3
MAMDC2
DUOX1
PNMA3
ACP7
SLC45A3
RNF212
EPCIP
SELENOP
ATP1A3
ELAVL2
PNLDC1
SPEF1
TOX
CR1
EPHA5
CFP
LYPD1
IRAG2
CLEC2L
TFCP2L1
TTC23L-AS1
SPATA17
CFAP276
SCN1A
CD6
CD101
LINC01088
FGF10
LINC01354
DUSP4
MS4A6A
NECAB1
FLJ33534
GABRG2
LOC100130587
FHIP1A
PDE1B
NPIPB15
ANKRD18B
PON3
ARGLU1-DT
EDNRB
MS4A4A
GPR22
LRRC10B
CLSPN
CYTIP
MYBPHL
RASGRF1
CD38
SDK1
SPP1
ENPP2
KRT19
BEST4
TPBGL
KCNMB2
DENND1C
ALS2CL
VSTM2L
CCDC39
IP6K3
HBA2
NRN1
LINC02346
PVT1
SLC5A4-AS1
CD33
LOC124904710
REM2
SLC1A5
HPSE2
SYT6
LOC728488
C1orf115
CHD5
ADM
SYT4
SLC5A11
GPR12
MYOZ1
MAPK8IP3-AS1
CPVL
INTS4P2
ADH1B
ST6GALNAC5
CYTL1
LGI2
GAP43
GPR183
CCN3
SYTL2
CYP1B1-AS1
GALR1
GRIN2A
FRMPD2
MILR1
SDK2
SIGLEC14
SLC16A8
NPTX2
DRAXIN
BAIAP2L2
CCKBR
SNX20
LILRA1
EFCC1
RASGEF1C
EYA1
SPTBN5
NEURL1B
HAPLN1
NRG1
HBB
HYDIN
RGS18
ASGR1
ZNF541
ZNF90
BASP1-AS1
CDCA5
SERPINH1
CHRNA7
RASD2
SMIM24
CFAP54
NEGR1
RAD54L
NPTX1
FGF12
EGR4
KIRREL2
OSGIN1
CDCA7
RPH3AL-AS1
PPP1R26-AS1
ITIH2
LRFN5
CLXN
CXCR4
NNMT
GRM4
ANLN
HRH1
DMRT2
SECTM1
OR2L13
KCNH4
PTGIS
IL1RAPL2
LINC01480
C1QTNF4
PLBD1
LMOD1
OBSCN
POMC
CNTN6
OBI1-AS1
WNT9B
CFAP53
PODNL1
PIP5K1B
EBI3
FBLN5
ADGRA1
THRB
GAS2L2
GNRH1
LRRC37A6P
ATF3
CFD
LMO4
KCNJ6
TACR1
MPZL2
NIPAL4
KCNE4
NTSR1
SLC26A9
ABI3BP
ZNF728
TMEM52B
EIF4E1B
BVES
OTOS
PNPLA3
CARNS1
RASEF
FHL2
PACRG-AS3
ZDHHC22
H2BC8
SNCB
ADRA2C
HES4
KCNN3
ACAN
TMEM144
TRDN
CERCAM
NTNG2
SYT13
P2RY6
NKX6-2
SLC22A6
CPNE7
SNX10
GPR156
C1QC
DYNLRB2
MIR219A2HG
CKMT1A
ANXA1
SLC14A1
HMOX1
SEZ6
ALOX15B
TDRD10
IL1RL2
LINC02193
CADPS2
GDPD3
P2RX6
HNF4G
LURAP1L
FCGR1CP
LOC283731
LINC01616
LINC00486
INHBA
LILRA2
CFAP96
SH2D6
TRIM61
LILRB3
SRPX2
CHST6
HTR5A
SHISAL1
NEUROD2
GPR65
BAG3
SCN4B
B3GAT1-DT
TCIM
TMEM72-AS1
KCNA4
FAR2P3
COL8A2
IQGAP2
GNG5
VENTX
DMKN
PTTG1
FAM47E
SEMA7A
SCRT1
ADAM11
LOC158434
TF
MARCHF3
SUSD3
TNFRSF11A
FUT1
PLEKHA4
CRYAB
COL23A1
TMC6
FLVCR2
SELL
NUPR1
EXPH5
SYT1
HPDL
KCNS3
EXTL1
PAX8-AS1
IGFBP2
FAM222A
NOTUM
ITPR1-DT
RASGEF1B
MYRF
ST18
DNAH9
DMRTA1
BEND5
EFEMP1
LOC116435278
RNASE6
LINC00622
ZIC2
LRRK1
CHAC1
TEX29
GPR83
OLFM4
ZNF676
HSPA2
LRRIQ1
MKRN7P
GABRE
PRSS3
ADAMTSL1
ABCA8
CHAD
SYTL4
SIGLEC8
CA10
SUSD5
NANOS3
IER3
RAB7B
TGFBR3L
KANSL1-AS1
LPAR1
DLX2
GEM
ERFE
DPEP2
PRKG2
LINC01116
SH3GL2
UGT8
ERMN
ULBP3
TBC1D10C
KIF12
LINC00937
CA8
FOLH1
HGFAC
UCP2
CFTR
DNAI1
AMIGO2
LINC03048
SCN1B
SATB2
GPR17
PPP1R14C
ANKRD24
ATP6V1C2
RGS6
LOC107985177
CCDC177
SPATA13
TFAP2C
TWIST1
C1QB
SLC4A10
SLC7A3
RPL23AP21
PLP1
PEX5L
LOC102724428
ZP3
LRP2
EGFL8
B3GALT2
ATP8B1
MARCHF11
GPR3
TMEM191B
ADCY1
TNFRSF12A
C1QA
HEYL
SOCS3
ERICH5
CD163L1
PLVAP
PMAIP1
PCDH11X
EMP1
FCER1G
LOC124902439
ALDH1A1
VSIG4
NELL2
TMEM221
PDGFRL
LILRB4
PTGES3L
IGSF1
MSH2-OT1
CCDC175
KIF19
DRD5
CFAP99
ADAMTS16
LINC01123
HUNK
ETNPPL
DAAM2
PLPP2
S100A10
GCAWKR
TSHZ3
LOC124905349
TLR10
FGF1
SMIM17
FZD2
C7
VESTAR
PTPN5
CD86
TEX30
STOM
LIME1
PLPPR1
CAPN3
IL32
RAC2
CCDC85A
NR4A2
LINC00877
GSN
PIP5KL1
KCNK2
CYP26B1
CD226
TSHZ2
RHOF
UNC13C
TRGC2
ACE
SHANK1
ECM2
CAMK2A
STRIP2
RBP7
CRHBP
GPIHBP1
NIPAL2
SOX11
FLJ32255
APOE
TMEM125
IGFL4
HPGD
GJB1
HTR4
SLITRK4
GRIP2
NFIA-AS2
SULT1B1
LRRC25
ZNF350-AS1
SPDEF
HSPB1
HSPA1B
SPATA31H1
ECRG4
LINC01331
GRIK1
PAK1
ICAM1
FLRT2-AS1
KLHL1
FBLN1
MT1G
ADORA3
FRMD4B
SH3RF2
RDH5
CCDC81
LINC00683
KYNU
LINC01664
TOX-DT
LINC01561
RPS2P46
ZIC5
SNHG18
LILRB2
SLC25A41
PLS1
INAVA
MIAT
KLHL13
SMIM10L2B
ELF4
TEKTIP1
CKMT1B
PDLIM1
GREM1
CRABP2
SIRPB2
CCL28
FHL5
SCG2
PNMA6A
SCN5A
TAGLN
ARPP21
SNCG
BTC
NOG
BBC3
GPR68
RIMS3
HLA-F-AS1
SLC10A4
LRRC56
PHF24
KCNJ2
IQCD
SEMA6A-AS1
FPR1
CMTM7
DPP10-AS1
ADAMTS4
PRKAR1B
SYT16
C3AR1
MYLK
DNAH14
SIDT1
RCVRN
ECM1
TG
ARL17B
TBX19
LINC02884
MOG
ZBTB7C
ZFP36
C19orf18
HTR1B
WNT16
CSF2RB
PROCR
SHROOM3
MMP2
TNFRSF13C
ISLR2
ESRRB
SOX8
CHML
NEK5
TMEM26
TMEM266
GABRQ
PWRN3
PI16
EVC2
KCNK13
CASZ1
BEX5
HLA-DQA1
KIF25
CEL
C5AR1
UBE2QL1
CCDC102A
ENOSF1
LINC01018
MBNL3
NPR3
GPRIN3
GRAMD2A
GIMAP5
APOBR
KHDRBS2
MYOT
DIAPH3
TYMS
IKBKE
ID3
GALNT9
PPP1R1B
NHIP
BASP1
ZNF467
HPR
RTP4
BOK
TSPAN2
ST8SIA5
THBS2
LINGO1
HLA-DRA
MYO1G
CLCA4
DNAH2
CTXN2
EMILIN3
ACAP1
CDA
LITAF
BCL11B
ULBP2
SFRP2
SEMA3E
MPO
EVI2A
SFRP1
FABP7
STEAP4
ZIC4
PIH1D2
HSD52
POLQ
MAGEC3
CYP2D6
SLC6A20
SPN
TMEM63A
GSTT2B
NDNF
PDE1A
CASP1
RUNX3
NAPB
TMPRSS3
AGBL4
MUC1
TEX15
IL18R1
PRKCH
FAM106A
PRSS36
CEDORA
FLJ16779
BMS1P10
CPED1
COL13A1
MAST1
LINC02177
ABCG4
LINC01414
SELPLG
POU3F1
SDS
NPTXR
OCA2
CCDC144A.1
PLIN4
ATP2A3
NTSR2
ERICH6-AS1
RAB17
MLLT11
KCNK3
ITGB2
CCDC184
CNDP1
PAK3
CD74
CA2
TLR7
ARHGAP28
LXN
GPR37
NFATC2
SMAGP
NFE2L1-DT
ALOXE3
MOBP
TMEFF1
ADAMTS3
GRIN2D
G0S2
ANGPT1
OSTM1-AS1
XK
FTCD
PDE3A
NEXN
ANGPTL4
NLRP2
FILIP1L
BCAS1
FA2H
KIF6
NECTIN1
IGFBP5
HLA-DOA
EPB41
LINC02371
LIX1
AOC3
CACNG4
AZGP1
GNLY
CHRNA10
AGMAT
MS4A7
PDP1
PTPRH
SOWAHA
CLDN11
INA
TRIM7
CDH18
PLA2G5
PTPRC
NAP1L2
RNF182
LINC01102
YWHAH
CCN1
TXNIP
OPCML
CCR1
LOC101927401
CDH12
RSPH1
RBM20
CCDC88C
STON1
ASB4
IFITM10
GJA5
COL4A5
LY6G5C
GABRA5
MRC1
TRIB3
C19orf38
LILRB1
WHRN
COLEC11
LMO1
ZC3HAV1L
HAPLN2
FGF17
CAMK2N2
CITED2
FMO4
SLC6A17
PNPLA5
COL14A1
THCAT155
SEMA3C
CFAP61
ADAMTS10
LRFN2
KMO
LOC400499
SMOC2
JAKMIP1
DCDC1
OLFM1
RASGRP3
SLCO1A2
CCDC17
CDKL1
ADRA1D
CDCP1
LOC102724019
TMIE
LRRC37A
ADAM12
H3C6
CDH19
SLC6A9
TLR5
SPATA41
LDB3
PTPRT-DT
NCF4
DGAT2
NECAB2
RPS18P5
STX11
HLA-DQB1
RTN4R
F7
HRH3
ADM5
EDA2R
SNAP91
PRELID2
C13orf46
RHBDL3
CD37
DIO3
SLC15A3
RPL17P50
ANTXR1
CYBRD1
LSP1
CNTNAP5
CLUL1
THPO
FMO3
CH25H
RERG
HAAO
SLFN12
LPAR5
CFAP43
TAGLN3
RTL9
LOC124909426
TRIM71
PLA1A
MBP
NAPSA
LUM
LGR5
TTC9B
PLCG2
LY86
PTGFR
AIDAP2
MYL9
CHGB
ARL4C
ERBB3
CNP
RBM11
FRK
RANBP17
PPM1N
VAMP8
SNX31
CAMK2N1
HTR7
SIGLEC10
RASGRF2
RAB6D
PDIA2
SLC47A1
CDHR1
TEX26
GABRG3
GPR160
CYBB
ITGB4
SNCAIP
ALPK1
MGST1
CLIC4
PIWIL2
CHRD
LTB4R2
MCTP2
ARHGAP36
LOXL4
HSD11B1
LINC02236
CISH
NNAT
SLC7A14-AS1
F5
TMEM273
CDH22
CNN2
PTGER4
SERPINA1
EBF1
RND1
CAPN13
PKN2-AS1
ARL4A
CD9
TMEM51-AS1
VIM
SP100
MIMT1
DNM1
CYP11A1
LINC00639
ZC3H12A
SYP
DEPDC7
ALOX5AP
AGER
C2orf73
GBP3
PPM1K-DT
FZD10-AS1
LAMA1
GRM7
UBASH3B
BHMT2
ZNF215
PPP1R14A
SLC11A1
COL6A3
TGFBI
KITLG
PNMA8C
ARHGEF19
OXR1
PLPP4
MN1
CNGA4
RGS9
CIMAP3
RGR
PRELP
LINC01637
GIPC3
BTN2A2
MIR223HG
DHRS3
LAIR1
BMPER
EFHB
FAM27E3
METTL27
SLC35D2
TRIM72
ASAH2
ABCA4
C1QTNF3
ITGA8
HIF1A-AS3
CDC42EP1
NETO2
HS3ST5
PACRG-AS1
NRG4
EPPK1
LST1
PIP4K2A
FAP
HES5
SYNPR
SHCBP1
CNTN3
TMEM176A
NWD1
PCSK6
IL10RA
NOX5
STARD5
CECR2
AQP6
VSTM2A
KHDRBS3
LAPTM5
CRTAC1
PLCB2
CPXM2
LSM11
KCNQ1
SP9
ZNF385D
DPYSL3
TBX18
CHN1
CYBA
DUSP9
SPATA18
COL9A3
PPM1E
CSPG4P12
MNDA
NKAIN4
SULT4A1
ADAMTS9
PRICKLE1
CEROX1
GABRD
EPCAM-DT
TRAIP
PMP22
TRIM59
DIRAS1
APOBEC3C
CAHM
LINC03002
TAC3
FBN3
KCNQ5
VRK2
LRRC3
BGN
SLC37A2
PARVG
CPNE5
STAB1
SDC4
TMEM255A
INHBA-AS1
IL20RA
RAB4B
PTAFR
DDO
PRPH2
PNMA2
OLFML3
LCP1
CSF1R
SLC31A2
DIPK1C
IGLON5
EFHD1
ADAT3
DCLK1
MOB3B
ARC
FAM83G
LOC105369306
CREB3L1
RERGL
F13A1
KCNJ16
KCNT2
NQO1
GPR34
CLEC3B
MYO16
SMYD2
DKK2
ERBB2
SAMSN1
CCN2
FCGR1A
DNMT3B
STXBP5-AS1
LOC105376244
COL20A1
ZIC3
STON2
RXRG
RHCE
IL15
MRGPRF
HEY2
SDC1
SLFN13
TMT1B
LGALS3BP
LY6G5B
NTNG1
FCGR2A
OLFML1
FCGR3A
SLC16A9
LINC01166
CD8B2
CACNG2
ZFP36L1
JPH1
KCNN1
RNASEK
CDC42EP3
ADAMTS19
CGAS
WIF1
PLEKHH1
PLEKHA7
ABCA10
PDE9A
SCIMP
PLEK
EHBP1-AS1
RBM47
ROPN1B
TNFRSF10D
RYR3-DT
MAL
STXBP5L
SASH3
ANKRD2
CNIH3
IL18
HSP90B2P
EVI2B
MEGF10
AOAH
BDKRB2
ANXA2R-AS1
SLC16A7
CCDC169
CEBPA
RTN4RL1
SOX10
GALNT12
COL9A2
LY6H
SCX
TGFA
RASAL3
EFHD2
LOC112268198
RNASE1
PIK3R5
WNT10B
LOC100506274
PDZRN4
RPL13AP26
LINC02054
PDXP
FOLR2
FMOD
PLEKHG5
CRLF1
LCA5L
LINC01779
DNAH10
ACTA2
TFEC
FYB1
NXPH4
P2RY1
FRZB
NPY5R
HSPB6
PHLDB2
CORO2A
SCART1
ZNF426-DT
GALNT15
ZNF603P
NINJ2
LINC01551
FABP6
UNC5CL
PTK2B
CTNNA3
GRID2
LTBP1
ITGA9
IGDCC3
ANOS1
ZFP36L2
YWHAH-AS1
ZNF236-DT
MICB
PGF
FHOD3
KRT18P4
GBP1
HS3ST1
FAM107B
AMH
ABCC3
MIF4GD-DT
PABPC1L2B
IFI44L
KIF5A
ATP1B1
LOC124904535
SPESP1
TSC22D4
SPSB1
LOC728138
ASPA
NT5DC3
GGTA1
LINC00649
FXYD1
SLC8A2
PRR22
KCNC1
MAN1A1
AHNAK2
CHRNA4
GAL3ST1
BRINP2
HRC
HBA1
PROSER2
OSBPL10
PRCD
MPP7
LY96
GPR4
MAFB
FAM124B
BTK
SCN2A
PHEX
PLA2R1
IQCJ-SCHIP1
GALNT14
OPALIN
PCDH8
ENPEP
RTKN
MAN2A1
SMIM5
GLI1
GCH1
CDC6
CLDND1
MT-RNR1
CNTN4
DSP
ASPHD2
GRHL1
HSPB7
DPP10
PRR18
SIX5
TMEM100
WWTR1
FBXL22
MMP14
KCNH8
PLEKHG3
BNIPL
BIN2
DOCK5
SOX2-OT
CX3CR1
PPP1R1A
CBX2
KCNA2
HLA-K
AMPH
HHATL
MSR1
STXBP1
NXPH1
MLKL
RIMBP2
MXRA5
PYDC1
GPAT2
STXBP2
LRRTM4
BAZ1A-AS1
LINC01265
SLC24A4
SYT10
EIF5A2
KCNC3
S1PR5
HMCN2
CDNF
MADCAM1
GRB7
CLEC4G
RMI2
PPP1CB-DT
AQP9
DNAJC22
PSMC3IP
GNAL
LINC00499
GJA1
HBQ1
SPATA1
KCNK12
IQSEC3
MTTP
VIM2P
TTYH2
FSCN2
FAM110A
LOC105373429
CMKLR1
KCNH1
BST2
ENO2
ATP6V1G2
TYROBP
CYP2D8P
NSG2
LYNX1
APOBEC3G
BMF
CRYBG3
FBLIM1
SLC44A1
VSIR
LOC105376387
MMD
RGS22
NRAP
MATN1-AS1
AK5
IKZF1
STX1A
GPRIN2
PIEZO2
C10orf90
KCNH6
CHADL
ITGB8
HECW1
PANX2
C2orf80
HAS1
MOXD1
CD93
FBXW7
TESC
CHAC2
TP53I11
LINC01285
ITGAX
STRC
EDIL3-DT
SFT2D2
SPACA6-AS1
KCNJ5
TNFSF9
VAV1
SHB
ANKDD1B
B3GALT5
PSTPIP2
TTLL9
RPL23AP5
IL12RB1
SEMA3D
LIN28B
SLC28A2-AS1
U2AF1
LOC105373780
SUGCT
RAB20
NAP1L3
FGL2
TMEM119
SEMA3B
PEBP4
RNU6-729P
TBX6
LINC02606
FGL1
PABPC1L2A
PRR5L
GIPC2
CCDC154
CABYR
GPR62
TBX15
GABBR2
TBXAS1
STX1B
FSIP2
R3HDM1
TMPRSS5
MYOM2
DMC1
ASXL3
FABP3
CCDC8
PLXNA1
GOLGA8B
CPAMD8
KCNIP4
DKFZp451B082
SHROOM4
HPN-AS1
EPDR1
IFITM2
PDZRN3
DEPP1
ZBTB20
KIAA1755
COL6A6
TSPAN13
CDH10
PILRB
ABCC6
ELOVL2-AS1
TMEM200A
PDGFD
PCAT19
ETV4
GPC6
ACTA2-AS1
NUAK2
GULP1
LTBP2
RAB6B
DCBLD1
PCARE
CLEC1A
LOC101928053
TENT5A
KCNG2
LTC4S
TMEM98
KCNH7
DPYS
DPYSL5
COL1A2
AKR1C3
LYG1
PIK3AP1
MTND2P28
IL17RA
MGAM
NAP1L5
DGKB
CSPG4P10
CEBPD
PKNOX2
SLC43A1
CLEC7A
EEIG2
PHACTR3-AS1
PSG8-AS1
MMD2
OXTR
LOC102724289
SNCA
A1BG
CACNG3
ARHGEF28
TP53INP2
TTC23-AS1
NOS1
LIN7A
MID1
FOXO1
LOC339059
CD14
LOC124909397
RASGRF2-AS1
TMC4
MRAP2
HIPK2
LOC105371115
MYH7B
PYCARD
INHBB
LINC00987
FTL
C21orf91
TDH-AS1
LACC1
BATF2
NAALADL1
KALRN
ITGA4
ACOT1
LOC122539214
EPHX1
LYVE1
BNC2
CLEC2B
CCDC136
FXYD6
GADD45A
RAB3A
NPR1
OMD
HTR5A-AS1
SYK
GNG7
LINC01608
AQP4
MKRN2OS
DNAH5
F11-AS1
CD84
PLXNB1
LOC100652758
IRF2-DT
SLITRK1
NR1I3
N4BP3
PBXIP1
HCLS1
SH3TC2
RAC3
APLF
ENTPD3
GLTP
LOC105370259
ESRRG
IFITM3
HIPK1-AS1
SLC25A35
PLP2
GRIA3
CILP2
SDF2L1
ADAMTS1
ITGA2
C1QL1
PTGES
RPS20P33
CTSS
MINDY2-DT
DRD4
COL21A1
WNT7B
SLC9A7
HPCAL1
ANKFN1
SNTB1
CPM
PHLDB1
LOC100130881
SLC7A7
LENG9
TLE2
ZFHX3
DGKH
CCSER1
ID4
H3-7
FER1L5
AIRE
FIGNL2
CSRP1-AS1
HSPG2
BMAL2
H2AJ
TMEM163
RPRML
MATN3
LRATD2
SNAP25-AS1
ADD3-AS1
SEZ6L2
FAM240C
VAT1
CYP2E1
FGD2
SYN2
IRF9
CD248
HAPLN3
PLEKHB1
COL27A1
CTF1
RHBDF2
GMPR
TMEM151B
NHLH2
SPHKAP
EOLA1-DT
SPNS1
DLGAP1
APOBEC3F
NPC2
RARRES2
LINC01310
RN7SL4P
TNFRSF10A
FUOM
RALY-AS1
PARD3
MIR3667HG
AKAP1-DT
SLC16A10
COL6A2
BATF3
EPHA4
HLA-DPA1
TUBA4A
HK2
TNS1
LRP5
MPP4
CAP2
KCNN4
LOC105372321
C2CD4D
APBB1IP
C1QTNF1
H2BC21
LOC105373390
PLXNB3
TNFAIP8L2
NR4A3
C11orf96
MEIS1
PIERCE2
LINC01588
LOC100996385
GPR153
SLC2A4
SLC7A9
ENDOU
SNURF
ZNF804A
ZIC1
RARB
KANK4
VTN
STAC3
LBH
MAP3K9
BAAT
MID1IP1
TMEM169
CHST5
HVCN1
SULT1C4
RGS10
DNASE1L2
YJEFN3
ANGPTL2
ZNF497
CLGN
FBXW4P1
KLF4
SQOR
GINS4
UBQLN1-AS1
ADAMTS7
GBP2
FENDRR
PAIP2B
PTCHD4
ANPEP
NRG3
PTPRU
NPL
TMC8
ZNF681
C8orf34
TYMP
RAB43
CDKN1C
TNFAIP8
SLC6A11
INSYN2A
ZNF503
GNG3
ANKRD55
NTN4
CCDC170
ANXA2
SNRPA1-DT
LINC03026
ALCAM
GREM2
PKIB
TNK1
WFDC2
PRLHR
GALNT17
GSTM5
LYL1
ABI3
SPDYA
PCDHGA12
STYK1
CDKN1A
CEACAM19
PBX3
PLAAT4
FN1
ZNF252P-AS1
TMC2
LOC729654
PASK
LINC01411
UNC5A
CSRP1
CYP2U1-AS1
PRR7
LINC01012
BTG3
PRKCE
INPP5D
MB21D2
DENND3-AS1
FAM110D
ILRUN-AS1
MAP1LC3B2
GSG1L
AFF2
SYN3
DACH2
TNFRSF1B
HLA-DMB
IGSF21
CMTM5
NPM2
ATOH7
MXRA8
SMIM14-DT
STK32A
CBS
HHEX
CALN1
TSSK6
LOC105372401
APOD
UFSP1
H2BC19P
SPC24
NEBL-AS1
MAGEE2
DOC2A
PCDHGA1
ZNF730
LINC02609
SLC2A9
S100A11
ANGPT2
RENBP
LINC03014
EPHA7
TBC1D3L
SPI1
GAS2L3
EDN3
ITGAL
EFCAB5
ARHGEF25
NCF2
KLF2
CDH1
SLC4A2
PRICKLE3
AIF1L
TREM2
BLNK
CLSTN3
SLA
HLA-DRB1
FXN.1
DDIT4L
CSF1
LOC107987108
SPON2
TNFAIP2
GALNT6
SLC39A4
LINC01700
BAMBI
ASS1
LINC02802
SNHG22
RFTN1
RIMKLA
DKK1
MTCO1P12
PCED1B
AIF1
RPH3AL
IL1R1
THBS3-AS1
CARD8-AS1
ZFHX4-AS1
TEAD2
ITGA2B
SOX17
FLNC
SERPINF2
OLR1
LOC730183
SREBF1
CLDND2
SMAD6
TLR4
GMNN
FLNA
TMEM176B
EEIG1
SLC40A1
SLFNL1
BEAN1
LIMK1
WFIKKN1
ZNF433-AS1
SMPD3
IER5
SOX18
KCNAB1
BCL6B
STAR
NUAK1
SPOCK3
WIPF1
CXCL12
TMIGD3
LOX
TBX2-AS1
TPD52L1
LEAP2
FDXACB1
ITPKB
KCNK10
CCDC150
IL33
MIR7-3HG
CRB2
NDRG1
THAP12P8
FSTL5
SCG3
LOC105370169
TTPA
MAP1B
GLIPR1
BMP6
CALHM5
ENTPD2
ADGRG6
IGFBP4
FAM3C
KIAA1549L
MPEG1
HR
TMCC3
DDX3Y
CA14
TGIF1
HOGA1
CCDC144A
TNFRSF25
EIF2AK3-DT
STMN1
C1S
CCDC15-DT
THBS1
UCHL1
PLEKHG4
COL19A1
KEL
GRASLND
FAXC
MTUS1-DT
LOC100506403
SLC25A21-AS1
VSIG2
LRTM2
RHBDL1
PYGM
AJUBA
IGFBP3
CFAP44
SYCE1
MC1R
CERS2
ABCC11
PHGDH
LPCAT2
TFR2
LINC01625
PEG13
LIN37
THAP7-AS1
PANK1
CYP1B1
PDE7B
CBLN1
RAB13
LINC00926
MAP3K7CL
SGSM3
LOC102724768
LKAAEAR1
RNF122
SNAI2
MAL2
DSCC1
KIAA0040
WDR97
CBR3
DOCK8
KIAA1614
HMCN1
LOC100129434
TIAM2
ITGA5
ADNP-AS1
CCDC122
KCNE3
AKAP5
SGK2
C4orf50
IZUMO1
SELENBP1
FBLN2
TMCO4
CYP27A1
SYT7
TOGARAM2
ADAM19
INKA2
LOC441239
SEPTIN5
B4GALNT3
SLC4A9
CIITA
SMN2
MIR124-2HG
CRYM
PGR
WNT3
MIR210HG
CAV1
TMEM88
WNT4
MAFF
ZC3HAV1
HPRT1
MYH7
SCN7A
NDUFA13
CD40
NAIP
MLXIPL
NFAM1
NR2F2
ZNF300
LBHD1
ZIM2
TUBA1B
LOC105369329
CCDC160
LYPD5
NEB
SAMD15
P2RY12
IGSF10
SATB1
SYNGR1
MREG
HHIP
ZMYND12
LOC107985433
LINC01152
YBX3
LY75
CCDC89
TAGLN2
TANC1
HK3
DOCK10
ZFHX4
LOC285097
CSF3R
RELL2
TLR3
SLC12A1
TMEM132D
PTER
LIMK2
FXYD2
PSMB8-AS1
LTB4R
LINC00298
TBL1X
TTC23L
MICAL2
JMJD7
HMGCS1
CDKN2A
MARVELD1
TEX9
TMEM160
NRGN
CD82
ZNF516
C1R
SLC7A2
TGM2
SV2A
HDAC10
INAFM1
CABP7
CNTN2
AKAP3
ADGRE2
SCN8A
RIT2
IQANK1
CYP2J2
ERI3-IT1
CYP2S1
CDH9
ERC2
ADAMTSL4
TGFB1I1
WDFY4
B3GNT2
PTHLH
EPHA8
LOC105372432
FADS6
CLMN
AARSD1
GFRA1
KLF16
LAMP2
LOC100506474
FREM1
CTCF-DT
ZMYND15
LINC02615
PRKCD
TENT5C
DUSP15
ZNF208
ARHGAP27
ECHDC2
RPL13AP11
INHA
LOC400622
LOC105379199
LRRC1
TCHH
TPM2
TMEM47
NMB
BTBD17
MAPK13
GIMAP2
FNDC10
LINC02649
CFAP58-DT
SLC17A9
CRISPLD1
PLCH2
ARHGDIB
SYT15
ARHGAP30
TMT1A
HCK
MT-ATP8
CSMD1
ZNF697
SBK1
DDR1
NCKAP1L
C1QTNF2
SCN3B
RPS3AP6
CCDC3
PTGDS
COL15A1
SHC2
DAAM2-AS1
MEX3B
MYCL
NTN1
RYR3
SLC22A13
PI15
DNAH17
DISP3
LINC02021
STING1
LRRC55
CAMK2D
CLDN9
RASGRP2
ZNF813
CREB3L2
GPSM3
PMEPA1
GNA15
LRP4
ISM1
TTC36-AS1
MCAM
TOR4A
NECAB3
SLC22A14
MTHFD2
NUDT4
SLC16A11
MOB3C
PARD3B
GEMIN7-AS1
TCF7L1
MSTN
PRKCG
LCDR
SOD3
COLCA1
BORA
RBFOX3
KAZALD1
ADD2
GNG12
SCARF2
LOC102723370
STX16-NPEPL1
DNAAF8
C16orf74
MTCL1
KCNJ4
H4C16
ENTREP1
DOK7
TNFSF10
KDM7A-DT
FAM182A
ITGB5
MT-TP
DDIT4
TEAD4
THBD
TTLL6
ZNF578
ADGRA3P1
RN7SL471P
TCEAL6
EPHB2
SPINT1
SYPL2
ACADL
EMILIN1
RENO1
NIBAN1
IL13RA1
DHPS
CACHD1
SLC1A6
IMPG2
IRAG1
COL10A1
TRNP1
SLC36A1
TRIP10
LINC02389
USP27X
ISG20
SCN9A
ARK2C
MCF2
L1CAM
LGALS9
SYTL1
ARSL
GLRA2
PLIN2
LINC01550
LIFR
PDPN
SRGN
DAB1
NPNT
TRPV2
KCNA5
LOC124904288
RNF150
GPRC5B
PREX2
TAF1A-AS1
CFH
CKS2
CABCOCO1
ATG9B
SPAG8
GPC1-AS1
ATAD3C
MYO15B
INSM2
USP9Y
LINC02777
SGK1
PKMYT1
KIF1C
ID2
GREB1L
FGFR3
VEGFC
MAP7D2
SLC2A5
SYNJ2
GNG4
ARHGDIG
NOMO3
TNFRSF1A
GAL3ST4
DNAJB1
TMBIM1
SNX10-AS1
GIMAP1
SYTL3
APOL2
DACT3
SLC25A48
LINC02033
PLD5

## Retaining highly variable genes from RNAseq dataset

In [5]:
import pandas as pd
from statsmodels.robust.scale import mad

# Load your data
dataset_path = 'rnaseq_merged_13k.csv'
df = pd.read_csv(dataset_path, index_col=0)

# Calculate the Median Absolute Deviation (MAD) for each gene (column)
mad_values = df.apply(mad, axis=0)

# Rank the genes based on MAD values from most variable to least variable
ranked_genes = mad_values.sort_values(ascending=False).index.tolist()

# Select the top 4000 most variable genes
most_variable_genes = ranked_genes[:5000]

# Print the ranked list of genes
# print("Ranked genes from most variable to least variable:")
# print(ranked_genes)
# print('Top 4000 most variable genes:')
# print(most_variable_genes)

# Filter the DataFrame to keep only the top 4000 most variable genes
df_filtered = df[most_variable_genes]

# Save the filtered DataFrame to a new CSV file
new_csv_file_path = 'rnaseq_merged_5k.csv'
df_filtered.to_csv(new_csv_file_path)

# Random Forest - SHAP LOOCV

In [ ]:
# First Finding the hyperparameters by using 10-fold CV
# will use the hyper parameters later for the RF SHAP

## Hyperparam tuning

The following code was run directly in the terminal

In [ ]:
# the code was run on the terminal, so the number of jobs was set to 110

# params are set for the original dataset


# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV, cross_validate
from scipy.stats import randint, uniform
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import make_scorer, f1_score, precision_score, recall_score

# Load the metadata
metadata_path = 'metadata_merged.csv'
df_metadata = pd.read_csv(metadata_path, index_col=0)

# Load the dataset
dataset_path = 'rnaseq_merged_5k.csv'
df_features = pd.read_csv(dataset_path, index_col=0)

# Ensure the feature dataset is aligned and ordered according to the metadata index
df_features = df_features.loc[df_metadata.index]

# Define features and target variable
X = df_features
y = df_metadata['diagnosis']

# Initialize the RandomForestClassifier with balanced class weight
rf = RandomForestClassifier(random_state=42)

# Define the parameter distribution for RandomizedSearchCV
param_dist = {
    'n_estimators': randint(320, 1100),
    'max_depth': randint(10, 40),
    'min_samples_split': randint(2, 22),
    'min_samples_leaf': randint(1, 11),
    'max_features': ['sqrt', 'log2', 0.11, 0.14, 0.16, 0.18]  # Range between 10% to 90% of the features
}

# Define a stratified k-fold cross-validation strategy
stratified_kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# Setup RandomizedSearchCV with 100 iterations and 10-fold cross-validation, focusing on F1 score for class 1
f1_scorer = make_scorer(f1_score, average='binary', labels=[1])  # Corrected the average parameter if it's binary classification
random_search = RandomizedSearchCV(rf, param_distributions=param_dist, n_iter=100, cv=stratified_kfold, scoring=f1_scorer, random_state=42, n_jobs=110)
random_search.fit(X, y)

# Print the best hyperparameters and the best score obtained
print(f"Best parameters: {random_search.best_params_}")
print(f"Best score: {random_search.best_score_}")

# Use the best estimator to perform cross-validation, focusing on multiple metrics for both classes
rf_best = random_search.best_estimator_
cv_results = cross_validate(rf_best, X, y, cv=10, scoring={'f1_Control': make_scorer(f1_score, labels=[0], average='binary'),
                                                           'f1_AD': make_scorer(f1_score, labels=[1], average='binary'),
                                                           'precision_Control': make_scorer(precision_score, labels=[0], average='binary'),
                                                           'precision_AD': make_scorer(precision_score, labels=[1], average='binary'),
                                                           'recall_Control': make_scorer(recall_score, labels=[0], average='binary'),
                                                           'recall_AD': make_scorer(recall_score, labels=[1], average='binary'),
                                                           'roc_auc': 'roc_auc'})


# Print the cross-validation results for each metric for both classes
scoring_metrics = ['f1_Control', 'f1_AD', 'precision_Control', 'precision_AD', 'recall_Control', 'recall_AD', 'roc_auc']
for metric in scoring_metrics:
    print(f"Mean CV {metric}: {cv_results['test_' + metric].mean()}\n")

Results:

In [ ]:
Best parameters: {'max_depth': 38, 'max_features': 0.11, 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 722}
Best score: 0.9105036779880274
Mean CV f1_Control: 0.8834043425789714

Mean CV f1_AD: 0.8834043425789714

Mean CV precision_Control: 0.84239680102186

Mean CV precision_AD: 0.84239680102186

Mean CV recall_Control: 0.9331741090596823

Mean CV recall_AD: 0.9331741090596823

Mean CV roc_auc: 0.9040957627872611

### Random Forest shap primary code

The same hyperparameters were chosen for all the iterations

The code was run on the terminal,

In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import classification_report, accuracy_score
import shap
import pandas as pd
import pickle
from concurrent.futures import ProcessPoolExecutor, as_completed

def process_fold(train_ix, test_ix, X, y, metadata):
    test_individual_id = metadata.iloc[test_ix[0]]['individualID']
    train_individual_ids = metadata.iloc[train_ix]['individualID']

    # Exclude training data that has the same individualID as the test sample
    exclude_ix = train_individual_ids[train_individual_ids == test_individual_id].index
    train_ix = [ix for ix in train_ix if ix not in exclude_ix]

    X_train, X_test = X.iloc[train_ix, :], X.iloc[test_ix, :]
    y_train, y_test = y.iloc[train_ix], y.iloc[test_ix]

    model = RandomForestClassifier(
        n_estimators=722,
        max_depth=38,
        min_samples_split=5,
        min_samples_leaf=4,
        max_features=0.11,
        random_state=42
    )
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[0][1]  # Probability of being AD

    explainer = shap.TreeExplainer(model, feature_perturbation='tree_path_dependent', model_output='raw')
    shap_values = explainer.shap_values(X_test)
    
    relevant_shap_values = [v[1] for v in shap_values[0]]  # Extract the relevant values for class 1
    
    specimen_id = metadata.index[test_ix[0]]
    
    shap_values_dict = {X.columns[i]: relevant_shap_values[i] for i in range(len(relevant_shap_values))}
    
    results_dict = {
        'specimen_id': specimen_id,
        'correct': (y_pred[0] == y_test.iloc[0]),
        'label': y_test.iloc[0],
        'shap_values': shap_values_dict,
        'predictive_score': y_proba,
        'predicted_label': y_pred[0]
    }

    return results_dict

# Load data
dataset_path = 'rnaseq_merged_5k.csv'
X = pd.read_csv(dataset_path, index_col=0)
metadata = pd.read_csv('metadata_merged.csv', index_col=0)
metadata = metadata.sample(frac=1, random_state=42)
X = X.loc[metadata.index]
y = metadata['diagnosis']

# Execute Leave-One-Out Cross-Validation
loo = LeaveOneOut()
results = []

with ProcessPoolExecutor(max_workers=75) as executor:
    futures = [executor.submit(process_fold, train_ix, test_ix, X, y, metadata) for train_ix, test_ix in loo.split(X)]
    for future in as_completed(futures):
        results.append(future.result())

# Evaluate and report model performance
y_true = [result['label'] for result in results]
y_pred = [result['predicted_label'] for result in results]
accuracy = accuracy_score(y_true, y_pred)
report = classification_report(y_true, y_pred, target_names=['Control', 'AD'], digits=4)

print(f'Overall model accuracy: {accuracy:.2f}')
print(report)

# Save SHAP values dictionary
shap_values_per_sample = {result['specimen_id']: result for result in results}
with open('shap_5k_v2.pkl', 'wb') as f:
    pickle.dump(shap_values_per_sample, f)
print('SHAP values dictionary saved.')

KeyboardInterrupt:

Printed Results:

In [ ]:
Overall model accuracy: 0.88
              precision    recall  f1-score   support

     Control     0.8775    0.7628    0.8161       742
          AD     0.8795    0.9420    0.9097      1363

    accuracy                         0.8789      2105
   macro avg     0.8785    0.8524    0.8629      2105
weighted avg     0.8788    0.8789    0.8767      2105

SHAP values dictionary saved.

## Filtering shap values dictionary

### Checking the overall distribution

In [1]:
import pickle
with open('shap_5k_v2.pkl', 'rb') as f:
    results_dict = pickle.load(f)

In [3]:
# Initialize counters and accumulators
total_patients = 0
correctly_classified = 0
total_score = 0
num_scores_above_average = 0

# Analyze the dictionary
for entry in results_dict.values():
    if entry['label'] == 1:  # Check if the sample is a patient
        total_patients += 1
        if entry['correct']:
            correctly_classified += 1
            total_score += entry['predictive_score']

# Calculate average score if there are any correctly classified patients
average_score = total_score / correctly_classified if correctly_classified else 0

# Find number of patients with score above average
for entry in results_dict.values():
    if entry['label'] == 1 and entry['correct'] and entry['predictive_score'] > average_score:
        num_scores_above_average += 1

# Print results
print(f"Total number of patients: {total_patients}")
print(f"Number of correctly classified patients: {correctly_classified}")
print(f"Average predictive score among correctly classified patients: {average_score:.3f}")
print(f"Number of patients with scores above average: {num_scores_above_average}")

Total number of patients: 1363
Number of correctly classified patients: 1284
Average predictive score among correctly classified patients: 0.828
Number of patients with scores above average: 725

In [ ]:
# Tissue and study dictribution among filtered patient samples

import pandas as pd
metadata = pd.read_csv('metadata_merged.csv', index_col=0)

# Calculate the average predictive score for correctly classified patients
average_score = sum(v['predictive_score'] for v in results_dict.values() if v['label'] == 1 and v['correct']) / sum(1 for v in results_dict.values() if v['label'] == 1 and v['correct'])

# Filter to get specimen IDs of correctly classified patients with scores above average
above_average_patients = [v['specimen_id'] for v in results_dict.values() if v['label'] == 1 and v['correct'] and v['predictive_score'] > average_score]

# Check these specimen IDs in the metadata and get their tissue types and study
filtered_metadata = metadata.loc[metadata.index.isin(above_average_patients)]

# Count the number of samples in each tissue type and study
tissue_counts = filtered_metadata['tissue'].value_counts()
study_counts = filtered_metadata['study'].value_counts()

# Create a figure with two subplots
fig, ax = plt.subplots(2, 1, figsize=(8, 6))

# Plotting the histograms
ax[0].bar(tissue_counts.index, tissue_counts.values, color='darkblue')
ax[0].set_title('Distribution of filtered samples among tissue types')
ax[0].set_xlabel('Tissue Type')
ax[0].set_ylabel('Number of samples')

ax[1].bar(study_counts.index, study_counts.values, color='darkgreen')
ax[1].set_title('Distribution of filtered samples among datasets')
ax[1].set_xlabel('Study')
ax[1].set_ylabel('Number of samples')

# Improve layout and show the plot
plt.tight_layout()
# plt.show()

# Save the figure
fig.savefig('./figures/5k_v2_tissue_study_distributions_filtered_samples.png', dpi=900)

### Filtering the dictionary (by threshold)

In [1]:
import pickle
with open('shap_5k_v2.pkl', 'rb') as f:
    shap_values_per_sample = pickle.load(f)

In [3]:
# Count the number of correctly classified AD patients
correctly_classified_ad_patients = sum(
    1 for result in shap_values_per_sample.values() if result['correct'] and result['label'] == 1
)

print(f'Number of correctly classified AD patients: {correctly_classified_ad_patients}')

Number of correctly classified AD patients: 1284

In [4]:
import numpy as np
# This contains samples with higher than average predcition score among correctly-classified AD samples

# Calculate the average predictive score among AD correctly classified samples
average_score_ad_correct = np.mean([value['predictive_score'] for value in shap_values_per_sample.values() if value['label'] == 1 and value['correct']])

# Filter the dictionary to include only the samples that are AD (1), correctly classified, and have a predictive score higher than the average among AD correctly classified samples
filtered_dict = {key: value for key, value in shap_values_per_sample.items()
                 if value['label'] == 1 and value['correct'] and value['predictive_score'] > average_score_ad_correct}

print(f"Number of samples in the filtered dictionary: {len(filtered_dict)}")

Number of samples in the filtered dictionary: 725

In [5]:
f_d = {
    result['specimen_id']: {
        gene: shap_value for gene, shap_value in result['shap_values'].items() if shap_value > 0.00026
    }
    for result in filtered_dict.values()
}

In [15]:
# List of names to remove
names_to_remove = ['age_death', 'tissue', 'sex', 'apoe4_allele']

# Create a dictionary with specimen ID as key and sorted list of genes (by SHAP values) as values
filtered_dict_genes_only = {
    specimen_id: sorted(
        (gene for gene in shap_values.keys() if gene not in names_to_remove),
        key=lambda gene: shap_values[gene],
        reverse=True
    )
    for specimen_id, shap_values in f_d.items()
}

In [16]:
with open('shap_samples_genes_5k.pkl', 'wb') as f:
    pickle.dump(filtered_dict_genes_only, f)

## 3. GSEA for genes common among the tissue samples

In [1]:
import pickle
with open('shap_samples_genes_5k.pkl', 'rb') as f:
    shap_values_per_sample = pickle.load(f)

In [ ]:
shap_values_per_sample

In [3]:
import pandas as pd

# Load your metadata and assume 'specimen_id' is the index
metadata = pd.read_csv('metadata_merged.csv', index_col=0)
metadata

,individualID,diagnosis,tissue,race,spanish,apoe4_allele,sex,batch,pmi,RIN,RIN2,age_death,AlignmentSummaryMetrics_PCT_PF_READS_ALIGNED,RnaSeqMetrics_PCT_INTRONIC_BASES,RnaSeqMetrics_PCT_INTERGENIC_BASES,RnaSeqMetrics_PCT_CODING_BASES,ethnicity,study
specimenID,,,,,,,,,,,,,,,,,,
487_120515,R9904978,0,3,1.0,2.0,0,0,4,12.433333,6.9,47.61,72.720055,0.931411,0.225013,0.058488,0.342722,NaN,ROSMAP
182_120424,R9818080,0,3,1.0,2.0,0,0,7,16.000000,8.4,70.56,81.111567,0.944450,0.172408,0.041036,0.394201,NaN,ROSMAP
193_120424,R9817161,1,3,1.0,2.0,0,1,4,1.750000,7.1,50.41,80.906229,0.958718,0.203963,0.048166,0.357855,NaN,ROSMAP
694_120605,R9817056,0,3,1.0,2.0,0,0,4,6.416667,7.1,50.41,87.753593,0.960609,0.201002,0.045065,0.397276,NaN,ROSMAP
366_120502,R9809661,1,3,1.0,2.0,1,1,7,17.416667,7.4,54.76,90.000000,0.931962,0.205742,0.048650,0.378299,NaN,ROSMAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948_CBE,948,1,2,NaN,NaN,0,1,24,4.000000,7.9,62.41,82.000000,0.971513,0.218398,0.102550,0.312080,NaN,MAYO
952_CBE,952,1,2,NaN,NaN,1,1,30,3.000000,9.0,81.00,83.000000,0.970183,0.289034,0.107290,0.266025,NaN,MAYO
966_CBE,966,1,2,NaN,NaN,2,1,22,16.000000,8.8,77.44,79.000000,0.971717,0.143079,0.069472,0.374848,NaN,MAYO
976_CBE,976,1,2,NaN,NaN,1,1,19,7.000000,8.3,68.89,90.000000,0.975052,0.134213,0.080812,0.370581,NaN,MAYO
991_CBE,991,1,2,NaN,NaN,1,0,27,12.077553,9.3,86.49,87.000000,0.966562,0.128365,0.122418,0.333899,NaN,MAYO

In [4]:
# Group specimen IDs by tissue
tissue_groups = metadata.groupby('tissue').groups

# Find common genes for each tissue
common_genes_by_tissue = {}
for tissue, indices in tissue_groups.items():
    # Filter gene lists that are associated with the current tissue's specimen IDs
    gene_lists = [shap_values_per_sample[specimen_id] for specimen_id in indices if specimen_id in shap_values_per_sample]
    
    # Find the intersection of all gene lists in this tissue
    if gene_lists:  # Ensure there are gene lists to intersect
        common_genes = set(gene_lists[0])  # Start with the genes of the first specimen
        for genes in gene_lists[1:]:
            common_genes.intersection_update(genes)  # Intersect with the genes of each subsequent specimen
        common_genes_by_tissue[tissue] = common_genes
    else:
        common_genes_by_tissue[tissue] = set()  # No common genes if no gene lists

# Print common genes for each tissue
for tissue, genes in common_genes_by_tissue.items():
    print(f"Common genes in tissue {tissue}: {genes}")

Common genes in tissue 1: {'KANK2', 'A2ML1'}
Common genes in tissue 2: {'TRIP10', 'SLC5A3', 'ANGPT1', 'SVOP', 'PIRT', 'RBM3', 'KCNJ10'}
Common genes in tissue 3: {'SCG2', 'PTPRU', 'SST', 'ROBO2', 'PDE10A', 'LPL', 'GFOD1', 'KCNF1', 'THCAT155'}
Common genes in tissue 4: {'LINC00499'}
Common genes in tissue 5: {'ANGPT1', 'SLC25A48'}
Common genes in tissue 6: {'SCG2', 'MDH1B', 'SST', 'PTPRU', 'PDE10A', 'PRDM16-DT', 'RHCE', 'PCP4L1', 'SDSL', 'SNAP25-AS1', 'LPL', 'GFOD1', 'KCNF1', 'NGB', 'THCAT155'}
Common genes in tissue 7: {'PCYOX1L', 'SAMD4A', 'NWD1', 'ITPKB'}
Common genes in tissue 8: {'KCNJ10', 'SLC25A48'}
Common genes in tissue 9: {'TRIP10', 'NWD1', 'CSRP1', 'GAREM2', 'SLC6A12', 'FAM106A', 'LPL', 'SVOP', 'DUSP4', 'THCAT155', 'SLC4A11', 'GAD1', 'EPCIP', 'ALDH1A1', 'QDPR', 'AHNAK', 'KCNJ10', 'MT1F', 'KANK2', 'APLN', 'A2ML1', 'ITPKB', 'A4GALT', 'NPNT', 'S100A4', 'EMP3', 'PCYOX1L', 'TEAD2', 'PRMT8', 'PDE10A', 'ANGPT2', 'PRELP', 'LOC116435278', 'SLC7A2', 'GPRASP2', 'FKBP5'}

In [5]:
# Print common genes for each tissue, each on a new line
for tissue, genes in common_genes_by_tissue.items():
    print(f"Tissue {tissue}:")
    for gene in genes:
        print(gene)
    print()  # Adds an empty line for better separation between tissues

Tissue 1:
KANK2
A2ML1

Tissue 2:
TRIP10
SLC5A3
ANGPT1
SVOP
PIRT
RBM3
KCNJ10

Tissue 3:
SCG2
PTPRU
SST
ROBO2
PDE10A
LPL
GFOD1
KCNF1
THCAT155

Tissue 4:
LINC00499

Tissue 5:
ANGPT1
SLC25A48

Tissue 6:
SCG2
MDH1B
SST
PTPRU
PDE10A
PRDM16-DT
RHCE
PCP4L1
SDSL
SNAP25-AS1
LPL
GFOD1
KCNF1
NGB
THCAT155

Tissue 7:
PCYOX1L
SAMD4A
NWD1
ITPKB

Tissue 8:
KCNJ10
SLC25A48

Tissue 9:
TRIP10
NWD1
CSRP1
GAREM2
SLC6A12
FAM106A
LPL
SVOP
DUSP4
THCAT155
SLC4A11
GAD1
EPCIP
ALDH1A1
QDPR
AHNAK
KCNJ10
MT1F
KANK2
APLN
A2ML1
ITPKB
A4GALT
NPNT
S100A4
EMP3
PCYOX1L
TEAD2
PRMT8
PDE10A
ANGPT2
PRELP
LOC116435278
SLC7A2
GPRASP2
FKBP5

### Filtering dataset and metadata -- export csv

Code for creating csv of selected patients (criteria applied)

In [31]:
import pandas as pd
import pickle

# Load the dictionary from the pickle file
with open('shap_samples_genes_5k.pkl', 'rb') as f:
    filtered_dict_genes_only = pickle.load(f)

# Load the RNA-seq counts dataset
rnaseq_counts = pd.read_csv('rnaseq_merged_5k.csv', index_col=0)

# Load the metadata
metadata = pd.read_csv('metadata_merged.csv', index_col=0)

# Filter the metadata to keep only the samples that are keys in the dictionary
filtered_metadata = metadata.loc[filtered_dict_genes_only.keys()]

# Filter the RNA-seq counts dataset to keep only the samples that are keys in the dictionary
filtered_rnaseq_counts = rnaseq_counts.loc[filtered_dict_genes_only.keys()]

# Merge the filtered RNA-seq counts dataset with the corresponding filtered metadata
merged_dataset = pd.merge(filtered_metadata, filtered_rnaseq_counts, left_index=True, right_index=True)

# Save the merged dataset to a CSV file
output_path = 'rnaseq_meta_rf_5k.csv'
merged_dataset.to_csv(output_path)
print(f'Merged dataset saved to {output_path}')

Merged dataset saved to rnaseq_meta_rf_5k_aug23.csv

# Clustering tissue samples into subtissues

Perform K-means clustering

The features are the union of shap genes for the patients in the tissue

Clustering each tissue and save a new csv file

In [1]:
import pandas as pd
df = pd.read_csv('rnaseq_meta_rf_5k.csv', index_col=0)
df

,individualID,diagnosis,tissue,race,spanish,apoe4_allele,sex,batch,pmi,RIN,...,GJB6,CCDC183-AS1,KLF15,AGTRAP,EZR,C2orf15,LMO2,GAREM2,ZBTB16,SDSL
specimenID,,,,,,,,,,,,,,,,,,,,,
hB_RNA_4411,AMPAD_MSSM_0000077445,1,5,1.0,2.0,1,1,14,6.583333,3.9,...,-0.591848,0.142189,0.371563,0.059603,0.059281,0.274474,0.357874,0.156186,-0.074227,-0.277443
hB_RNA_12484,AMPAD_MSSM_0000034015,1,4,1.0,2.0,1,1,20,5.250000,4.2,...,0.214412,-0.187430,-0.156292,-0.190344,0.008100,0.273406,0.056397,-0.258564,-0.294504,-0.404002
hB_RNA_16295,AMPAD_MSSM_0000083367,1,5,1.0,2.0,0,0,5,15.250000,10.0,...,0.101255,-0.134110,0.138174,0.277939,0.206213,-0.942221,0.589214,-0.088010,-0.189206,-0.178790
BM_10_674,AMPAD_MSSM_0000098979,1,4,1.0,2.0,0,1,21,19.333333,5.0,...,0.307214,0.853469,0.242229,0.054418,0.095695,-0.317063,-0.177276,0.088239,0.198327,0.010501
hB_RNA_16665,AMPAD_MSSM_0000034450,1,5,1.0,2.0,0,1,6,3.583333,9.9,...,-0.173683,0.519355,0.347839,0.285156,0.130551,-0.479695,0.286889,0.250938,-0.097065,-0.094118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
hB_RNA_7775,AMPAD_MSSM_0000077061,1,8,9.0,1.0,0,1,7,5.500000,9.9,...,-0.486417,0.537512,0.348259,0.237720,-0.034479,-0.072609,0.170131,0.223767,0.276840,0.480200
BM_36_545,AMPAD_MSSM_0000076188,1,7,1.0,2.0,0,0,18,5.733333,6.5,...,-0.573104,-0.220458,0.630038,0.585316,-0.106984,0.244389,0.238596,0.207993,-0.222866,-0.566743
Sample_R6636386-AC,R6636386,1,1,1.0,2.0,0,0,13,19.500000,6.0,...,-0.091409,-0.127889,0.173018,-0.006432,0.103108,-0.426582,0.099830,0.468877,-0.164213,0.234050
hB_RNA_16935,AMPAD_MSSM_0000019543,1,5,1.0,2.0,0,1,6,8.716667,9.8,...,-0.248578,0.091338,0.059089,0.404707,0.022760,-1.116050,0.318737,0.060726,-0.201323,0.016790
BM_22_37,AMPAD_MSSM_0000031969,1,8,1.0,2.0,0,0,28,4.500000,5.4,...,-0.663021,0.322928,0.355639,0.073581,0.196544,-0.171792,0.229818,0.029503,0.365303,-0.186236

The next code was iteratively done for each tissue (nine tissues total)

In [13]:
# Step 1, clustering and saving the labels

import pandas as pd
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

# Load the SHAP genes dictionary
with open('shap_samples_genes_5k.pkl', 'rb') as f:
    filtered_dict_genes_only = pickle.load(f)

# Load the dataset
df = pd.read_csv('rnaseq_meta_rf_5k.csv', index_col=0)

# Specify the tissue number
TISSUE_NUMBER = 9
df = df[df['tissue'] == TISSUE_NUMBER]

# Find the union of SHAP genes for all patients in the specified tissue
tissue_specimen_ids = df.index
shap_genes_union = set()

for specimen_id in tissue_specimen_ids:
    if specimen_id in filtered_dict_genes_only:
        shap_genes_union.update(filtered_dict_genes_only[specimen_id])
print(len(shap_genes_union))
# Filter the features to include only the SHAP genes in the union
filtered_features = df[list(shap_genes_union & set(df.columns[18:]))]  # Only include SHAP genes that are present in the dataset


# Perform K-means clustering
kmeans = KMeans(init="random", n_clusters=4, n_init=2000, max_iter=6000, random_state=42)
kmeans_labels = kmeans.fit_predict(filtered_features)


# Save the cluster labels to a file
label_df = pd.DataFrame({'specimen_id': df.index, 'cluster_label': kmeans_labels+1})
label_df['cluster_label'] = str(TISSUE_NUMBER) + '_' + label_df['cluster_label'].astype(str)
label_filename = f'/home/vmottaqi/rnaseq_synapse/cluster_labels_aug27/cluster_labels_for_tissue_{TISSUE_NUMBER}.csv'
label_df.to_csv(label_filename, index=False)

1046

In [26]:
# Step2, Assign_Labels_Script.py

import pandas as pd

# Specify the tissue number and corresponding cluster label file
TISSUE_NUMBER = 9  # Change this for each run (1, 3, 6)
CLUSTER_LABELS_FILE = f'/home/vmottaqi/rnaseq_synapse/cluster_labels_aug27/cluster_labels_for_tissue_{TISSUE_NUMBER}.csv'

# Load the dataset and the cluster labels
df = pd.read_csv('rnaseq_meta_rf_5k_with_clusters.csv', index_col=0)
cluster_labels = pd.read_csv(CLUSTER_LABELS_FILE, index_col='specimen_id')

# Check if 'clusters' column exists, if not, create it and insert at the fourth position
if 'clusters' not in df.columns:
    # Create the column with default values
    df.insert(3, 'clusters', pd.NA)  # Use None or np.nan if preferred
    
# Assign the new cluster labels to the 'clusters' column based on the index
df.loc[cluster_labels.index, 'clusters'] = cluster_labels['cluster_label']

# Save the updated dataframe
df.to_csv('rnaseq_meta_rf_5k_with_clusters.csv')

In [27]:
import pandas as pd
df = pd.read_csv('rnaseq_meta_rf_5k_with_clusters.csv', index_col=0)

df

,individualID,diagnosis,tissue,clusters,race,spanish,apoe4_allele,sex,batch,pmi,...,GJB6,CCDC183-AS1,KLF15,AGTRAP,EZR,C2orf15,LMO2,GAREM2,ZBTB16,SDSL
specimenID,,,,,,,,,,,,,,,,,,,,,
hB_RNA_4411,AMPAD_MSSM_0000077445,1,5,5_3,1.0,2.0,1,1,14,6.583333,...,-0.591848,0.142189,0.371563,0.059603,0.059281,0.274474,0.357874,0.156186,-0.074227,-0.277443
hB_RNA_12484,AMPAD_MSSM_0000034015,1,4,4_1,1.0,2.0,1,1,20,5.250000,...,0.214412,-0.187430,-0.156292,-0.190344,0.008100,0.273406,0.056397,-0.258564,-0.294504,-0.404002
hB_RNA_16295,AMPAD_MSSM_0000083367,1,5,5_2,1.0,2.0,0,0,5,15.250000,...,0.101255,-0.134110,0.138174,0.277939,0.206213,-0.942221,0.589214,-0.088010,-0.189206,-0.178790
BM_10_674,AMPAD_MSSM_0000098979,1,4,4_3,1.0,2.0,0,1,21,19.333333,...,0.307214,0.853469,0.242229,0.054418,0.095695,-0.317063,-0.177276,0.088239,0.198327,0.010501
hB_RNA_16665,AMPAD_MSSM_0000034450,1,5,5_3,1.0,2.0,0,1,6,3.583333,...,-0.173683,0.519355,0.347839,0.285156,0.130551,-0.479695,0.286889,0.250938,-0.097065,-0.094118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
hB_RNA_7775,AMPAD_MSSM_0000077061,1,8,8_3,9.0,1.0,0,1,7,5.500000,...,-0.486417,0.537512,0.348259,0.237720,-0.034479,-0.072609,0.170131,0.223767,0.276840,0.480200
BM_36_545,AMPAD_MSSM_0000076188,1,7,7_4,1.0,2.0,0,0,18,5.733333,...,-0.573104,-0.220458,0.630038,0.585316,-0.106984,0.244389,0.238596,0.207993,-0.222866,-0.566743
Sample_R6636386-AC,R6636386,1,1,1_3,1.0,2.0,0,0,13,19.500000,...,-0.091409,-0.127889,0.173018,-0.006432,0.103108,-0.426582,0.099830,0.468877,-0.164213,0.234050
hB_RNA_16935,AMPAD_MSSM_0000019543,1,5,5_2,1.0,2.0,0,1,6,8.716667,...,-0.248578,0.091338,0.059089,0.404707,0.022760,-1.116050,0.318737,0.060726,-0.201323,0.016790
BM_22_37,AMPAD_MSSM_0000031969,1,8,8_3,1.0,2.0,0,0,28,4.500000,...,-0.663021,0.322928,0.355639,0.073581,0.196544,-0.171792,0.229818,0.029503,0.365303,-0.186236

In [29]:
# Group by "Tissue clusters" and aggregate the data
cluster_summary = df.groupby('clusters').agg(
    number_of_rows=pd.NamedAgg(column='clusters', aggfunc='size'),  # Count the number of rows for each cluster
    unique_individuals=pd.NamedAgg(column='individualID', aggfunc='nunique')  # Count unique individuals in each cluster
)

# Print the resulting DataFrame
print(cluster_summary)

          number_of_rows  unique_individuals
clusters
1_1                    4                   4
1_2                   18                  18
1_3                   11                  11
1_4                   21                  21
2_1                    7                   7
2_2                    4                   4
2_3                    5                   5
2_4                    2                   2
3_1                   19                  19
3_2                   19                  19
3_3                   37                  37
3_4                   18                  18
4_1                   18                  18
4_2                   30                  30
4_3                   36                  33
4_4                   16                  15
5_1                   25                  23
5_2                   33                  33
5_3                   38                  35
5_4                   25                  25
6_1                    6                   6
6_2                    8                   8
6_3                   12                  12
6_4                    6                   6
7_1                   30                  27
7_2                    9                   9
7_3                   34                  31
7_4                   67                  58
8_1                   39                  37
8_2                   28                  27
8_3                   51                  45
8_4                   17                  15
9_1                    5                   5
9_2                   10                  10
9_3                    7                   7
9_4                    7                   7

# Identification of subtissue-specific biomarkers

In [7]:
import pandas as pd
import pickle

with open('shap_samples_genes_5k.pkl', 'rb') as f:
    specimen_genes_dict = pickle.load(f)

# Load the DataFrame
df = pd.read_csv('rnaseq_meta_rf_5k_with_clusters.csv', index_col=0)


# Prepare to track the intersection of genes in each cluster and the union of all genes across clusters
cluster_common_genes = {}
all_clusters_union = set()  # This will hold the union of all genes across all clusters

# Iterate over each cluster group in the DataFrame
for cluster, group in df.groupby('clusters'):
    # Get the list of specimen IDs for the current cluster
    specimen_ids = group.index.to_list()
    
    # Initialize a set for the intersection of genes for the first specimen ID, if it exists in the dictionary
    common_genes = set(specimen_genes_dict.get(specimen_ids[0], []))
    
    # Intersect the genes lists of all other specimen IDs in the cluster
    for specimen_id in specimen_ids[1:]:
        if specimen_id in specimen_genes_dict:
            common_genes.intersection_update(specimen_genes_dict[specimen_id])
    
    # Store the common genes for the current cluster
    cluster_common_genes[cluster] = common_genes
    
    # Update the union of all genes across clusters
    all_clusters_union.update(common_genes)

# Print the common genes for each cluster
# for cluster, genes in cluster_common_genes.items():
#     print(f"{cluster}: {len(genes)} common genes.")

# Print the number of unique genes found across all clusters
print(f"Total unique genes across all clusters: {len(all_clusters_union)}")
print(all_clusters_union)

Total unique genes across all clusters: 183
{'KCNK9', 'DDX11', 'SVOP', 'STEAP3', 'B3GAT1-DT', 'NPNT', 'VGF', 'EGR4', 'DUSP6', 'MOXD1', 'INSYN2A', 'APLN', 'SLC39A11', 'PPEF1', 'SEMA3C', 'KCNJ10', 'ALDH1A1', 'TRIP10', 'TNFRSF11B', 'LOC105376654', 'GRIK1', 'SLC16A6', 'CD38', 'SCIRT', 'SLC6A12', 'RALY-AS1', 'ENPEP', 'RIDA', 'PLCXD2', 'PHYHD1', 'SPRED3', 'RHCE', 'WDR76', 'NWD1', 'ANGPT1', 'APOBR', 'APLF', 'RERG', 'KANK2', 'PLK4', 'LRRC55', 'A4GALT', 'ARL17B', 'EPCIP', 'LOC116435278', 'COL21A1', 'NRIP2', 'SST', 'DUSP1', 'ENOSF1', 'SLC4A11', 'MSR1', 'HSD11B2', 'SPATA31H1', 'CSRP1', 'C4orf19', 'C4B', 'SPRY4', 'CNTNAP5-DT', 'ITGA10', 'DHRS11', 'GEM', 'FOXO4', 'ZBTB16', 'IGSF3', 'SLCO4A1', 'COL9A1', 'SCG2', 'DIO2', 'ROBO2', 'HBA2', 'CD44', 'BACE2', 'LINC01736', 'GFOD1', 'EIF2AK3-DT', 'EMP3', 'GOLGA8B', 'SFRP2', 'FKBP5', 'PIRT', 'SH2D5', 'SLC5A3', 'SLC6A9', 'LINC01310', 'MDH1B', 'COLEC12', 'BEX5', 'MPO', 'SNAP25-AS1', 'FAM106A', 'CHL1', 'KCNAB1', 'LTF', 'APLNR', 'PDE10A', 'MYCBPAP', 'PFKP', 'PRELP', 'SMIM10L2A', 'MILIP', 'RBM3', 'SAMD4A', 'CHST6', 'SLC7A2', 'ITPKB', 'ADAMTS2', 'SDSL', 'THCAT155', 'GAREM2', 'GAD2', 'NGB', 'TOMM70', 'KCNE4', 'WWTR1', 'PCYOX1L', 'MT1F', 'LPL', 'HSPB7', 'A2ML1', 'MDGA1', 'ARMCX5', 'JAG1', 'KCNF1', 'RRAD', 'ANGPT2', 'C2orf88', 'HBA1', 'FBLN2', 'PRDM16-DT', 'CHRDL1', 'PDYN', 'CRH', 'GAD1', 'AGFG2', 'HS6ST1', 'IRAK2', 'PAK1', 'SLC25A48', 'TRIM47', 'MEIS3', 'PTPRU', 'LINC00499', 'PADI2', 'AQP6', 'SCIN', 'GALR1', 'GOLGA7B', 'PRMT8', 'DUSP4', 'MIR9-1HG', 'PLPPR1', 'SMIM10L2B', 'IRS1', 'GMPR', 'AHNAK', 'GPRASP2', 'PPDPF', 'FMOD', 'OGN', 'PTTG1IP', 'COL24A1', 'TTTY14', 'TTC23-AS1', 'FBN3', 'SSC5D', 'ADPGK-AS1', 'PCP4L1', 'HBB', 'INHBA-AS1', 'HSD17B8', 'GLI1', 'ST6GAL2', 'DDIT4L', 'CALB1', 'LNCOC1', 'FANCE', 'PASK', 'TEAD2', 'RAPGEF4', 'QDPR', 'S100A4', 'PRKX'}

In [8]:
for i in all_clusters_union:
    print(i)

KCNK9
DDX11
SVOP
STEAP3
B3GAT1-DT
NPNT
VGF
EGR4
DUSP6
MOXD1
INSYN2A
APLN
SLC39A11
PPEF1
SEMA3C
KCNJ10
ALDH1A1
TRIP10
TNFRSF11B
LOC105376654
GRIK1
SLC16A6
CD38
SCIRT
SLC6A12
RALY-AS1
ENPEP
RIDA
PLCXD2
PHYHD1
SPRED3
RHCE
WDR76
NWD1
ANGPT1
APOBR
APLF
RERG
KANK2
PLK4
LRRC55
A4GALT
ARL17B
EPCIP
LOC116435278
COL21A1
NRIP2
SST
DUSP1
ENOSF1
SLC4A11
MSR1
HSD11B2
SPATA31H1
CSRP1
C4orf19
C4B
SPRY4
CNTNAP5-DT
ITGA10
DHRS11
GEM
FOXO4
ZBTB16
IGSF3
SLCO4A1
COL9A1
SCG2
DIO2
ROBO2
HBA2
CD44
BACE2
LINC01736
GFOD1
EIF2AK3-DT
EMP3
GOLGA8B
SFRP2
FKBP5
PIRT
SH2D5
SLC5A3
SLC6A9
LINC01310
MDH1B
COLEC12
BEX5
MPO
SNAP25-AS1
FAM106A
CHL1
KCNAB1
LTF
APLNR
PDE10A
MYCBPAP
PFKP
PRELP
SMIM10L2A
MILIP
RBM3
SAMD4A
CHST6
SLC7A2
ITPKB
ADAMTS2
SDSL
THCAT155
GAREM2
GAD2
NGB
TOMM70
KCNE4
WWTR1
PCYOX1L
MT1F
LPL
HSPB7
A2ML1
MDGA1
ARMCX5
JAG1
KCNF1
RRAD
ANGPT2
C2orf88
HBA1
FBLN2
PRDM16-DT
CHRDL1
PDYN
CRH
GAD1
AGFG2
HS6ST1
IRAK2
PAK1
SLC25A48
TRIM47
MEIS3
PTPRU
LINC00499
PADI2
AQP6
SCIN
GALR1
GOLGA7B
PRMT8
DUSP4
MIR9-1HG
PLPPR1
SMIM10L2B
IRS1
GMPR
AHNAK
GPRASP2
PPDPF
FMOD
OGN
PTTG1IP
COL24A1
TTTY14
TTC23-AS1
FBN3
SSC5D
ADPGK-AS1
PCP4L1
HBB
INHBA-AS1
HSD17B8
GLI1
ST6GAL2
DDIT4L
CALB1
LNCOC1
FANCE
PASK
TEAD2
RAPGEF4
QDPR
S100A4
PRKX

In [1]:
import pandas as pd
import pickle

with open('shap_samples_genes_5k.pkl', 'rb') as f:
    specimen_genes_dict = pickle.load(f)

# Load the DataFrame
df = pd.read_csv('rnaseq_meta_rf_5k_with_clusters.csv', index_col=0)


# Prepare to track the intersection of genes in each cluster and the union of these intersections
cluster_common_genes = {}
all_clusters_union_of_intersections = set()

# Iterate over each cluster group in the DataFrame
for cluster, group in df.groupby('clusters'):
    # Get the list of specimen IDs for the current cluster
    specimen_ids = group.index.to_list()
    
    # Initialize a set for the intersection of genes for the first specimen ID, if it exists in the dictionary
    common_genes = set(specimen_genes_dict.get(specimen_ids[0], []))
    
    # Intersect the genes lists of all other specimen IDs in the cluster
    for specimen_id in specimen_ids[1:]:
        if specimen_id in specimen_genes_dict:
            common_genes.intersection_update(specimen_genes_dict[specimen_id])
    
    # Store the common genes for the current cluster
    cluster_common_genes[cluster] = common_genes
    
    # Update the union of all cluster intersections
    if not all_clusters_union_of_intersections:
        all_clusters_union_of_intersections = common_genes.copy()
    else:
        all_clusters_union_of_intersections.intersection_update(common_genes)

# Print the common genes for each cluster
for cluster, genes in cluster_common_genes.items():
    print(f"{cluster}: {len(genes)} genes: {genes}")

# Print the unique number of genes common across all clusters
print(f"Unique number of genes common across all clusters: {len(all_clusters_union_of_intersections)}")

1_1: 46 genes: {'EIF2AK3-DT', 'COL9A1', 'ENOSF1', 'ADPGK-AS1', 'HBA1', 'SMIM10L2B', 'HBB', 'ARL17B', 'SLC16A6', 'C2orf88', 'SLC5A3', 'HBA2', 'IRS1', 'SLC7A2', 'CNTNAP5-DT', 'NWD1', 'MT1F', 'LOC116435278', 'PLPPR1', 'DHRS11', 'S100A4', 'PCYOX1L', 'MEIS3', 'KCNJ10', 'PIRT', 'ADAMTS2', 'IGSF3', 'GOLGA8B', 'KANK2', 'LPL', 'PPDPF', 'EMP3', 'ZBTB16', 'EPCIP', 'APLN', 'SLC25A48', 'A2ML1', 'LINC01736', 'PRMT8', 'AQP6', 'GLI1', 'SLC6A9', 'WDR76', 'SMIM10L2A', 'PFKP', 'ANGPT1'}
1_2: 21 genes: {'B3GAT1-DT', 'VGF', 'SMIM10L2B', 'MDGA1', 'SLC5A3', 'SVOP', 'SLC4A11', 'RBM3', 'S100A4', 'CSRP1', 'PCYOX1L', 'ITGA10', 'TRIP10', 'SPRED3', 'KANK2', 'MDH1B', 'SLC25A48', 'A2ML1', 'LINC01736', 'GAREM2', 'ROBO2'}
1_3: 18 genes: {'CSRP1', 'A2ML1', 'KCNJ10', 'GAREM2', 'SVOP', 'PRELP', 'TRIP10', 'SPRED3', 'IGSF3', 'SLC6A12', 'KANK2', 'ITPKB', 'SSC5D', 'AQP6', 'PCP4L1', 'VGF', 'S100A4', 'SMIM10L2B'}
1_4: 12 genes: {'SLC25A48', 'A2ML1', 'SLC5A3', 'PIRT', 'TRIP10', 'ST6GAL2', 'KANK2', 'B3GAT1-DT', 'DUSP1', 'EPCIP', 'VGF', 'SSC5D'}
2_1: 28 genes: {'APLNR', 'GMPR', 'AHNAK', 'NRIP2', 'VGF', 'SLC5A3', 'SVOP', 'SLC4A11', 'SLC7A2', 'SNAP25-AS1', 'BEX5', 'RBM3', 'NWD1', 'SSC5D', 'PRKX', 'KCNJ10', 'PIRT', 'TRIP10', 'KANK2', 'SLC25A48', 'FKBP5', 'SLCO4A1', 'TEAD2', 'PRELP', 'DUSP1', 'ANGPT1', 'SLC6A12', 'PHYHD1'}
2_2: 56 genes: {'MILIP', 'EIF2AK3-DT', 'SAMD4A', 'KCNE4', 'AHNAK', 'NPNT', 'THCAT155', 'PLK4', 'MIR9-1HG', 'GPRASP2', 'HBA1', 'SMIM10L2B', 'SLC16A6', 'GOLGA7B', 'C2orf88', 'SLC5A3', 'SPATA31H1', 'RRAD', 'HBA2', 'SVOP', 'SLC7A2', 'RAPGEF4', 'NWD1', 'RBM3', 'MT1F', 'ARMCX5', 'DHRS11', 'S100A4', 'CD38', 'CSRP1', 'GFOD1', 'PCYOX1L', 'MEIS3', 'KCNJ10', 'PIRT', 'ITGA10', 'TRIP10', 'SPRED3', 'LINC01310', 'DDIT4L', 'KANK2', 'RHCE', 'EMP3', 'MDH1B', 'SLC25A48', 'A2ML1', 'TEAD2', 'LINC01736', 'SLCO4A1', 'GAREM2', 'PRELP', 'SLC6A9', 'WDR76', 'DUSP1', 'PFKP', 'ANGPT1'}
2_3: 41 genes: {'EIF2AK3-DT', 'SAMD4A', 'INHBA-AS1', 'SLC39A11', 'AHNAK', 'DDX11', 'NRIP2', 'GPRASP2', 'SMIM10L2B', 'MDGA1', 'GOLGA7B', 'C2orf88', 'SLC5A3', 'SPATA31H1', 'SVOP', 'SLC4A11', 'RBM3', 'MT1F', 'ARMCX5', 'PCYOX1L', 'KCNJ10', 'ITGA10', 'PIRT', 'IGSF3', 'TRIP10', 'KANK2', 'TTTY14', 'PPEF1', 'EMP3', 'SCG2', 'EPCIP', 'LNCOC1', 'MDH1B', 'GAREM2', 'PRELP', 'FBLN2', 'SLC6A9', 'AQP6', 'GLI1', 'ANGPT1', 'SLC6A12'}
2_4: 80 genes: {'PDE10A', 'MPO', 'SAMD4A', 'RALY-AS1', 'QDPR', 'RRAD', 'SLC4A11', 'SLC7A2', 'ENPEP', 'SDSL', 'KCNJ10', 'FAM106A', 'DUSP1', 'LRRC55', 'VGF', 'DUSP6', 'HBA1', 'MDGA1', 'SCIN', 'PASK', 'HSD11B2', 'HBA2', 'PADI2', 'RBM3', 'MT1F', 'ANGPT2', 'ITGA10', 'PIRT', 'IGSF3', 'TRIP10', 'MSR1', 'EPCIP', 'APLN', 'SLC25A48', 'AQP6', 'ANGPT1', 'EIF2AK3-DT', 'B3GAT1-DT', 'HSD17B8', 'ADPGK-AS1', 'SEMA3C', 'ARL17B', 'APOBR', 'SLC5A3', 'CHST6', 'DIO2', 'SSC5D', 'TRIM47', 'RHCE', 'FKBP5', 'TEAD2', 'SLCO4A1', 'GAREM2', 'PTPRU', 'SLC6A9', 'SLC6A12', 'SPRY4', 'NRIP2', 'DDX11', 'ITPKB', 'KCNK9', 'C2orf88', 'SVOP', 'KCNF1', 'CHRDL1', 'PCP4L1', 'DUSP4', 'CNTNAP5-DT', 'STEAP3', 'S100A4', 'CSRP1', 'AGFG2', 'EGR4', 'SPRED3', 'DDIT4L', 'EMP3', 'JAG1', 'SST', 'LINC01736', 'PFKP'}
3_1: 26 genes: {'PDE10A', 'INHBA-AS1', 'THCAT155', 'NRIP2', 'FANCE', 'APOBR', 'RIDA', 'KCNF1', 'SLC4A11', 'IRS1', 'TTC23-AS1', 'CD38', 'SDSL', 'GFOD1', 'ADAMTS2', 'LPL', 'ALDH1A1', 'SCG2', 'SST', 'AQP6', 'FBLN2', 'SLC6A9', 'PTPRU', 'WDR76', 'ROBO2', 'SNAP25-AS1'}
3_2: 26 genes: {'PDE10A', 'THCAT155', 'C4orf19', 'SLC16A6', 'SLC5A3', 'CHRDL1', 'KCNF1', 'SLC7A2', 'PCP4L1', 'SNAP25-AS1', 'LOC116435278', 'GFOD1', 'MOXD1', 'ADAMTS2', 'RHCE', 'LPL', 'ZBTB16', 'EPCIP', 'SCG2', 'MDH1B', 'SLC25A48', 'SST', 'PRMT8', 'PTPRU', 'ROBO2', 'PFKP'}
3_3: 15 genes: {'PDE10A', 'GFOD1', 'SST', 'PIRT', 'KCNF1', 'PTPRU', 'THCAT155', 'ROBO2', 'LPL', 'CD38', 'INSYN2A', 'LOC116435278', 'NGB', 'PFKP', 'SCG2'}
3_4: 31 genes: {'PDE10A', 'EIF2AK3-DT', 'SAMD4A', 'THCAT155', 'GAD1', 'VGF', 'FANCE', 'KCNF1', 'SLC7A2', 'IRS1', 'PCP4L1', 'PADI2', 'LOC116435278', 'TTC23-AS1', 'CD38', 'CRH', 'GFOD1', 'ADAMTS2', 'SPRED3', 'KANK2', 'LPL', 'SCG2', 'EPCIP', 'MDH1B', 'SST', 'SLCO4A1', 'PRMT8', 'PTPRU', 'ROBO2', 'HSPB7', 'SLC6A12'}
4_1: 4 genes: {'PIRT', 'EPCIP', 'SLC5A3', 'LINC00499'}
4_2: 6 genes: {'SLC5A3', 'LINC00499', 'SSC5D', 'ANGPT1', 'VGF', 'S100A4'}
4_3: 5 genes: {'PIRT', 'SLC4A11', 'LINC00499', 'CNTNAP5-DT', 'NWD1'}
4_4: 31 genes: {'GMPR', 'INHBA-AS1', 'AHNAK', 'LINC00499', 'NPNT', 'ITPKB', 'VGF', 'SLC5A3', 'SVOP', 'KCNF1', 'SLC7A2', 'PCP4L1', 'NWD1', 'DHRS11', 'SSC5D', 'COL24A1', 'MEIS3', 'PIRT', 'IGSF3', 'ST6GAL2', 'PPEF1', 'EMP3', 'EPCIP', 'SLC25A48', 'FKBP5', 'PRELP', 'A4GALT', 'ROBO2', 'DUSP1', 'ANGPT1', 'PHYHD1'}
5_1: 36 genes: {'SAMD4A', 'AHNAK', 'LINC00499', 'NPNT', 'GPRASP2', 'ITPKB', 'VGF', 'SVOP', 'SLC4A11', 'PCP4L1', 'CNTNAP5-DT', 'NWD1', 'LOC116435278', 'STEAP3', 'SSC5D', 'S100A4', 'CSRP1', 'ANGPT2', 'PCYOX1L', 'KCNJ10', 'PIRT', 'IGSF3', 'ST6GAL2', 'TRIP10', 'KANK2', 'SCG2', 'SLC25A48', 'FKBP5', 'GAREM2', 'PRMT8', 'LTF', 'ROBO2', 'DUSP1', 'HSPB7', 'ANGPT1', 'BEX5'}
5_2: 9 genes: {'SLC25A48', 'A2ML1', 'ADAMTS2', 'PRELP', 'PCP4L1', 'KANK2', 'RBM3', 'ANGPT1', 'EPCIP'}
5_3: 11 genes: {'SLC25A48', 'ITGA10', 'PIRT', 'IGSF3', 'SLC6A9', 'NPNT', 'NWD1', 'RBM3', 'ANGPT1', 'ITPKB', 'SSC5D'}
5_4: 29 genes: {'APLNR', 'AHNAK', 'SLC6A12', 'GPRASP2', 'ITPKB', 'MDGA1', 'SLC16A6', 'PCP4L1', 'CNTNAP5-DT', 'NWD1', 'RBM3', 'MT1F', 'CRH', 'CSRP1', 'ANGPT2', 'PCYOX1L', 'ITGA10', 'PIRT', 'ST6GAL2', 'KANK2', 'APLN', 'GALR1', 'SLC25A48', 'PRELP', 'SLC6A9', 'ROBO2', 'DUSP1', 'ANGPT1', 'BEX5'}
6_1: 54 genes: {'PRDM16-DT', 'PDE10A', 'LOC105376654', 'EIF2AK3-DT', 'SAMD4A', 'INHBA-AS1', 'MYCBPAP', 'THCAT155', 'COL9A1', 'FANCE', 'ARL17B', 'APOBR', 'SLC16A6', 'GOLGA7B', 'SLC5A3', 'HBA2', 'CHRDL1', 'KCNF1', 'SLC7A2', 'IRS1', 'FBN3', 'SNAP25-AS1', 'PCP4L1', 'RBM3', 'TNFRSF11B', 'LOC116435278', 'TTC23-AS1', 'NGB', 'S100A4', 'CD38', 'ANGPT2', 'SDSL', 'GFOD1', 'COL21A1', 'MOXD1', 'ADAMTS2', 'RHCE', 'LPL', 'ALDH1A1', 'SCG2', 'APLN', 'EPCIP', 'MDH1B', 'SST', 'SLCO4A1', 'PLCXD2', 'PRELP', 'FBLN2', 'PTPRU', 'SLC6A9', 'WDR76', 'LTF', 'PFKP', 'PDYN'}
6_2: 47 genes: {'PRDM16-DT', 'PDE10A', 'LOC105376654', 'SAMD4A', 'THCAT155', 'C4orf19', 'HBA1', 'APOBR', 'SLC5A3', 'HBA2', 'RIDA', 'KCNF1', 'SLC7A2', 'SLC4A11', 'SNAP25-AS1', 'FBN3', 'PCP4L1', 'CHRDL1', 'LOC116435278', 'PLPPR1', 'NGB', 'S100A4', 'SDSL', 'COL21A1', 'GFOD1', 'ITGA10', 'ADAMTS2', 'MOXD1', 'TRIP10', 'KANK2', 'LPL', 'PPDPF', 'RHCE', 'ALDH1A1', 'SCG2', 'EPCIP', 'MDH1B', 'SLC25A48', 'TEAD2', 'SST', 'LINC01736', 'PRMT8', 'GLI1', 'PTPRU', 'ROBO2', 'ANGPT1', 'PFKP'}
6_3: 39 genes: {'PRDM16-DT', 'PDE10A', 'LOC105376654', 'EIF2AK3-DT', 'THCAT155', 'C4orf19', 'MIR9-1HG', 'ADPGK-AS1', 'FANCE', 'RIDA', 'KCNF1', 'PADI2', 'IRS1', 'PCP4L1', 'APLF', 'SNAP25-AS1', 'NGB', 'CD38', 'SDSL', 'GFOD1', 'COL21A1', 'RHCE', 'LPL', 'PPDPF', 'TOMM70', 'SCG2', 'APLN', 'MDH1B', 'SLC25A48', 'SST', 'GAREM2', 'AQP6', 'PTPRU', 'WDR76', 'SLC6A9', 'ROBO2', 'PFKP', 'SLC6A12', 'PDYN'}
6_4: 47 genes: {'PRDM16-DT', 'PDE10A', 'INHBA-AS1', 'RERG', 'AHNAK', 'NPNT', 'THCAT155', 'C4orf19', 'MIR9-1HG', 'LRRC55', 'VGF', 'FANCE', 'RIDA', 'KCNF1', 'FBN3', 'SLC4A11', 'PCP4L1', 'CNTNAP5-DT', 'IRAK2', 'LOC116435278', 'NGB', 'MT1F', 'S100A4', 'CRH', 'KCNAB1', 'ANGPT2', 'SDSL', 'GFOD1', 'ADAMTS2', 'SPRED3', 'KANK2', 'LPL', 'RHCE', 'ALDH1A1', 'SCG2', 'EPCIP', 'MDH1B', 'COLEC12', 'SST', 'PRMT8', 'AQP6', 'PTPRU', 'WDR76', 'ROBO2', 'HSPB7', 'SNAP25-AS1', 'SLC6A12'}
7_1: 11 genes: {'SLC25A48', 'PDE10A', 'TEAD2', 'PCYOX1L', 'SAMD4A', 'SLC4A11', 'LTF', 'NWD1', 'RBM3', 'ITPKB', 'SSC5D'}
7_2: 43 genes: {'PDE10A', 'SAMD4A', 'KCNE4', 'AHNAK', 'LINC00499', 'NPNT', 'B3GAT1-DT', 'GPRASP2', 'ITPKB', 'VGF', 'QDPR', 'GEM', 'SMIM10L2B', 'ARL17B', 'SCIN', 'SLC5A3', 'SH2D5', 'SVOP', 'KCNF1', 'SLC7A2', 'PCP4L1', 'SLC4A11', 'CNTNAP5-DT', 'CHST6', 'NWD1', 'CHL1', 'DHRS11', 'PRKX', 'ANGPT2', 'PCYOX1L', 'KCNJ10', 'MEIS3', 'PIRT', 'SPRED3', 'DDIT4L', 'SCG2', 'FKBP5', 'TEAD2', 'PRMT8', 'PRELP', 'ROBO2', 'ANGPT1', 'PAK1'}
7_3: 46 genes: {'GMPR', 'SAMD4A', 'KCNE4', 'AHNAK', 'NPNT', 'GAD1', 'GPRASP2', 'ITPKB', 'SMIM10L2B', 'SCIN', 'SVOP', 'SLC4A11', 'SLC7A2', 'PCP4L1', 'CHST6', 'NWD1', 'STEAP3', 'ARMCX5', 'DHRS11', 'SSC5D', 'S100A4', 'CSRP1', 'ANGPT2', 'PCYOX1L', 'AGFG2', 'KCNJ10', 'PIRT', 'TRIP10', 'GOLGA8B', 'KANK2', 'EMP3', 'PPEF1', 'APLN', 'SLC25A48', 'FKBP5', 'COLEC12', 'TEAD2', 'GAREM2', 'PRELP', 'PRMT8', 'A4GALT', 'ROBO2', 'DUSP1', 'ANGPT1', 'BEX5', 'PHYHD1'}
7_4: 17 genes: {'CSRP1', 'DHRS11', 'PCYOX1L', 'SAMD4A', 'PRMT8', 'PIRT', 'IGSF3', 'AHNAK', 'LINC00499', 'ROBO2', 'CHST6', 'NWD1', 'GPRASP2', 'ANGPT1', 'ITPKB', 'APLN', 'PHYHD1'}
8_1: 8 genes: {'SLC25A48', 'FKBP5', 'KCNJ10', 'SVOP', 'ROBO2', 'CNTNAP5-DT', 'NWD1', 'RBM3'}
8_2: 9 genes: {'SLC25A48', 'ANGPT2', 'PCYOX1L', 'KCNJ10', 'SAMD4A', 'PRELP', 'SLC7A2', 'ANGPT1', 'EPCIP'}
8_3: 12 genes: {'SLC25A48', 'FKBP5', 'PCYOX1L', 'KCNJ10', 'SAMD4A', 'SVOP', 'PIRT', 'ROBO2', 'CNTNAP5-DT', 'GPRASP2', 'ITPKB', 'APLN'}
8_4: 30 genes: {'APLNR', 'SAMD4A', 'AHNAK', 'GPRASP2', 'ITPKB', 'VGF', 'QDPR', 'DUSP6', 'SVOP', 'SLC4A11', 'PCP4L1', 'CHST6', 'NWD1', 'MT1F', 'ARMCX5', 'CSRP1', 'ANGPT2', 'PCYOX1L', 'MEIS3', 'KCNJ10', 'PIRT', 'ST6GAL2', 'SLC25A48', 'FKBP5', 'PRMT8', 'SLC6A9', 'ROBO2', 'ANGPT1', 'BEX5', 'PHYHD1'}
9_1: 73 genes: {'PDE10A', 'APLNR', 'GMPR', 'AHNAK', 'SLC6A12', 'NPNT', 'THCAT155', 'C4orf19', 'GAD1', 'LRRC55', 'GPRASP2', 'ITPKB', 'VGF', 'QDPR', 'FOXO4', 'SLC5A3', 'SVOP', 'SLC4A11', 'SLC7A2', 'PCP4L1', 'DUSP4', 'IRAK2', 'CNTNAP5-DT', 'CHST6', 'RBM3', 'TNFRSF11B', 'NWD1', 'LOC116435278', 'MT1F', 'ARMCX5', 'SSC5D', 'WWTR1', 'S100A4', 'PRKX', 'CSRP1', 'ANGPT2', 'COL21A1', 'PCYOX1L', 'AGFG2', 'KCNJ10', 'FMOD', 'TRIP10', 'SPRED3', 'FAM106A', 'DDIT4L', 'KANK2', 'LPL', 'ALDH1A1', 'EMP3', 'TOMM70', 'SCG2', 'APLN', 'EPCIP', 'SLC25A48', 'FKBP5', 'A2ML1', 'COLEC12', 'TEAD2', 'SLCO4A1', 'LINC01736', 'GAREM2', 'PRELP', 'PRMT8', 'PTPRU', 'LTF', 'OGN', 'A4GALT', 'SLC6A9', 'ROBO2', 'DUSP1', 'PTTG1IP', 'BEX5', 'PHYHD1'}
9_2: 49 genes: {'APLNR', 'PDE10A', 'GMPR', 'LOC105376654', 'KCNE4', 'AHNAK', 'LINC00499', 'NPNT', 'THCAT155', 'GAD1', 'LRRC55', 'GPRASP2', 'ITPKB', 'QDPR', 'SVOP', 'SLC4A11', 'SLC7A2', 'PCP4L1', 'DUSP4', 'NWD1', 'LOC116435278', 'MT1F', 'WWTR1', 'S100A4', 'HS6ST1', 'CSRP1', 'ANGPT2', 'PCYOX1L', 'KCNJ10', 'TRIP10', 'FAM106A', 'KANK2', 'LPL', 'ALDH1A1', 'EMP3', 'TOMM70', 'EPCIP', 'APLN', 'FKBP5', 'A2ML1', 'SLCO4A1', 'TEAD2', 'GAREM2', 'PRELP', 'PRMT8', 'SLC6A9', 'A4GALT', 'DUSP1', 'SLC6A12'}
9_3: 59 genes: {'PDE10A', 'LOC105376654', 'KCNE4', 'AHNAK', 'LINC00499', 'NPNT', 'THCAT155', 'C4orf19', 'GAD1', 'LRRC55', 'GPRASP2', 'ITPKB', 'QDPR', 'C4B', 'SCIN', 'CD44', 'SLC5A3', 'SVOP', 'SLC4A11', 'SLC7A2', 'DUSP4', 'IRAK2', 'NWD1', 'MT1F', 'GRIK1', 'LOC116435278', 'BACE2', 'S100A4', 'HS6ST1', 'CSRP1', 'ANGPT2', 'PCYOX1L', 'KCNJ10', 'ADAMTS2', 'TRIP10', 'FAM106A', 'DDIT4L', 'KANK2', 'LPL', 'ALDH1A1', 'EMP3', 'TOMM70', 'CALB1', 'APLN', 'EPCIP', 'SLC25A48', 'FKBP5', 'A2ML1', 'TEAD2', 'LINC01736', 'GAREM2', 'PRELP', 'PRMT8', 'LTF', 'A4GALT', 'ROBO2', 'SFRP2', 'SLC6A12', 'PHYHD1'}
9_4: 64 genes: {'PDE10A', 'GMPR', 'LOC105376654', 'AHNAK', 'LINC00499', 'THCAT155', 'NPNT', 'GAD1', 'GPRASP2', 'ITPKB', 'QDPR', 'GEM', 'HBB', 'SLC5A3', 'SVOP', 'SLC4A11', 'SLC7A2', 'DUSP4', 'IRAK2', 'CHST6', 'RBM3', 'NWD1', 'LOC116435278', 'MT1F', 'TTC23-AS1', 'ARMCX5', 'DHRS11', 'BACE2', 'S100A4', 'NGB', 'GAD2', 'CSRP1', 'ANGPT2', 'PCYOX1L', 'AGFG2', 'KCNJ10', 'ADAMTS2', 'TRIP10', 'FAM106A', 'DDIT4L', 'KANK2', 'LPL', 'ALDH1A1', 'EMP3', 'EPCIP', 'APLN', 'SCIRT', 'MDH1B', 'FKBP5', 'SLC25A48', 'A2ML1', 'TEAD2', 'SLCO4A1', 'LINC01736', 'GAREM2', 'PRELP', 'PRMT8', 'PTPRU', 'SLC6A9', 'AQP6', 'A4GALT', 'ROBO2', 'DUSP1', 'SLC6A12'}
Unique number of genes common across all clusters: 6

# Differential Gene Expression Anlaysis

The following codes were run in R

In [ ]:
# Assume 'd' is your count data file, and 'metadata' contains covariates
# Load data
counts_1 <- read.csv("~/rnaseq_synapse/rnaseq_merged.csv", row.names=1)
metadata <- read.csv("~/rnaseq_synapse/metadata_merged.csv", row.names=1)

In [ ]:
counts <- t(counts_1)
head(counts)

          487_120515 182_120424 193_120424 694_120605 366_120502 52_120416
GSTM1     -4.215604  2.902852   -3.402193  -4.469664  -4.994719  5.122827
CARTPT     6.834142  5.157342    4.849398   6.151414   5.015698  3.806240
MIR3976HG  6.178734  7.094175    7.094800   5.166871   6.056921  5.993219
LINC02263  6.555866  5.924674    5.939845   5.443188   5.746971  5.356559
PVALB      4.856445  6.263663    6.501796   5.560515   6.019998  5.741306
LINC00507  7.831509  8.437083    8.088912   7.370465   7.071019  6.368210
          493_120515 602_120523 391_120503 188_120424 ⋯ 896_CBE
GSTM1     2.969968   -4.708235  2.526440   -2.673994  ⋯ -3.31100115
CARTPT    4.795244    5.881344  6.456524    4.440356  ⋯ -0.27987369
MIR3976HG 6.792772    7.236313  5.736064    7.326071  ⋯ -0.15449599
LINC02263 5.768771    6.163136  6.416249    5.662262  ⋯  0.03759164
PVALB     5.784334    5.834687  5.903117    6.421346  ⋯  0.44419848
LINC00507 6.186820    7.599045  6.885997    7.887401  ⋯  0.04459388
          931_CBE      933_CBE    937_CBE    946_CBE   948_CBE     952_CBE
GSTM1      4.053918635  3.8355694 -3.2075176 4.3492333  4.77991058  4.5304002
CARTPT    -0.363123243  0.8756968  0.1986972 0.4173184  0.02551019  0.5558833
MIR3976HG  1.797874935  0.4017159 -0.9945479 1.4034774 -1.06753751  0.8596794
LINC02263  0.001537356 -1.1270682  0.6299782 0.4910610  0.33333973  1.1974926
PVALB     -0.148561636 -0.4236383 -1.3158033 0.3327168  0.76226449 -1.2344991
LINC00507 -0.010224784 -1.1966923  0.4678591 0.5911319  0.32626223  1.1071664
          966_CBE    976_CBE     991_CBE
GSTM1     -3.7107536  3.87415208 -3.1878292
CARTPT    -0.7678034 -0.98572085 -2.0726406
MIR3976HG  0.6392938  0.01455088  0.1754143
LINC02263 -0.1513534 -0.47793894 -1.7754383
PVALB      0.3633605  0.38996223 -1.5912605
LINC00507 -0.2048866 -0.49502489 -1.6901069

In [ ]:
head(metadata)

           individualID diagnosis tissue race spanish apoe4_allele sex batch
487_120515 R9904978     0         3      1    2       0            0   4
182_120424 R9818080     0         3      1    2       0            0   7
193_120424 R9817161     1         3      1    2       0            1   4
694_120605 R9817056     0         3      1    2       0            0   4
366_120502 R9809661     1         3      1    2       1            1   7
52_120416  R9809441     1         3      1    2       0            1   6
           pmi       RIN RIN2  age_death
487_120515 12.433333 6.9 47.61 72.72005
182_120424 16.000000 8.4 70.56 81.11157
193_120424  1.750000 7.1 50.41 80.90623
694_120605  6.416667 7.1 50.41 87.75359
366_120502 17.416667 7.4 54.76 90.00000
52_120416   4.450000 6.4 40.96 90.00000
           AlignmentSummaryMetrics_PCT_PF_READS_ALIGNED
487_120515 0.931411
182_120424 0.944450
193_120424 0.958718
694_120605 0.960609
366_120502 0.931962
52_120416  0.962062
           RnaSeqMetrics_PCT_INTRONIC_BASES RnaSeqMetrics_PCT_INTERGENIC_BASES
487_120515 0.225013                         0.058488
182_120424 0.172408                         0.041036
193_120424 0.203963                         0.048166
694_120605 0.201002                         0.045065
366_120502 0.205742                         0.048650
52_120416  0.226173                         0.049418
           RnaSeqMetrics_PCT_CODING_BASES ethnicity study
487_120515 0.342722                                 ROSMAP
182_120424 0.394201                                 ROSMAP
193_120424 0.357855                                 ROSMAP
694_120605 0.397276                                 ROSMAP
366_120502 0.378299                                 ROSMAP
52_120416  0.395452                                 ROSMAP

In [ ]:
metadata$diagnosis <- factor(metadata$diagnosis, levels = c("0", "1"), labels = c("Control", "AD"))
metadata$tissue <- factor(metadata$tissue)

metadata$study <- factor(metadata$study)

In [ ]:
# Prepare model matrix
mm <- model.matrix(~ diagnosis + study, data=metadata)

In [ ]:
# Fit the linear model
fit <- lmFit(counts, mm)
head(coef(fit))

          (Intercept) diagnosisAD studyMSBB  studyROSMAP
GSTM1      0.3206458  -0.2917390   0.1762688 -0.5531683
CARTPT     4.2743872  -0.4582374  -5.3315086 -0.6137951
MIR3976HG  2.2705723  -0.1861391  -3.3336617  2.0303998
LINC02263  3.3011125  -0.2504035  -4.1926690  1.1128123
PVALB     -2.0760926  -0.2906812   1.6581763  6.3135228
LINC00507  3.9759612  -0.5774913  -4.0452469  1.7171972

In [ ]:
# Apply empirical Bayes statistics
fit <- eBayes(fit)

#contrast.matrix <- makeContrasts(ADvsControl = diagnosis, levels=mm)
contrast.matrix <- makeContrasts(ADvsControl = diagnosisAD, levels=mm)

Warning message in makeContrasts(ADvsControl = diagnosisAD, levels = mm):
“Renaming (Intercept) to Intercept”

In [ ]:
head(contrast.matrix)

             Contrasts
Levels        ADvsControl
  Intercept   0
  diagnosisAD 1
  studyMSBB   0
  studyROSMAP 0

In [ ]:
fit2 <- contrasts.fit(fit, contrast.matrix)
fit2 <- eBayes(fit2)

head(coef(fit2))

           Contrasts
            ADvsControl
  GSTM1     -0.2917390
  CARTPT    -0.4582374
  MIR3976HG -0.1861391
  LINC02263 -0.2504035
  PVALB     -0.2906812
  LINC00507 -0.5774913

In [ ]:
results <- topTable(fit2, adjust="bonferroni", sort.by="P", number=Inf)
head(results, 10)

       logFC     AveExpr     t        P.Value      adj.P.Val    B
KANK2  0.4530560 -0.06193903 20.71727 6.289386e-87 3.144693e-83 187.1975
A2ML1  0.5590949 -0.17512053 20.05148 5.411257e-82 2.705629e-78 175.9110
SAMD4A 0.3855109 -0.12977807 19.86115 1.330607e-80 6.653036e-77 172.7304
EMP3   0.4735810 -0.20496027 19.24238 3.824434e-76 1.912217e-72 162.5345
GAREM2 0.4875128 -0.11546230 19.14487 1.889235e-75 9.446177e-72 160.9482
PHYHD1 0.4944209 -0.21006990 19.13521 2.212490e-75 1.106245e-71 160.7913
TRIP10 0.5142339 -0.15778843 19.04131 1.023968e-74 5.119840e-71 159.2698
ITPKB  0.5173538 -0.08207957 18.92630 6.641132e-74 3.320566e-70 157.4132
S100A4 0.8002347 -0.27885291 18.72633 1.681409e-72 8.407047e-69 154.2042
PRELP  0.5572362 -0.21158359 18.57322 1.963609e-71 9.818045e-68 151.7638

In [ ]:
length(which(results$adj.P.Val < 0.05))

[1] 2347

In [ ]:
write.csv(results, "~/rnaseq_synapse/differential_expression_results_5k.csv")